Repository angr/angr, pull requests merged in 2018-02, with the labels that each got.

#856 find_merge_points: remove dead code
  angr/analyses/cfg/cfg_utils.py
Labels: refactor

#862 Fix/cfg accurate crashes
  angr/analyses/cfg/cfg_accurate.py
Labels: bug

#874 Remove section/segment querying code from CFGBase
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/x86_elf_pic_plt.py
  angr/analyses/reassembler.py
Labels: refactor

#880 SimEngineVEX: Add a special cace when checking the block cache.
  angr/engines/vex/engine.py
Labels: enhancement

#881 Remove depricated concrete_parts() from symbolic memory
  angr/state_plugins/symbolic_memory.py
Labels: refactor

#882 Remove unnecessary loop reference to memory in controlled_data._concretize
  angr/concretization_strategies/controlled_data.py
Labels: refactor

#884 Block: Default to read_bytes_c() for faster reads.
  angr/block.py
Labels: enhancement
