Repository angr/angr, pull requests merged in 2018-03, with the labels that each got.

#868 Move graph-related algorithms to utils/graph.py
  angr/analyses/cdg.py
  angr/analyses/veritesting.py
  angr/misc/__init__.py
  angr/misc/graph.py
  angr/utils/__init__.py
  angr/utils/graph.py
  tests/test_cdg.py
Labels: refactor

#883 CFGFast: Make popping pending jobs much faster.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#892 Keystone integration
  angr/engines/hub.py
  angr/factory.py
  angr/manager.py
  tests/test_keystone.py
Labels: feature

#900 Fix for arch name in cfg_fast.py
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#901 Identifier: Remove the dependency to angrop.
  angr/analyses/identifier/identify.py
Labels: refactor

#902 Fix test case regression_memcmp_definite_size. It now works under Windows.
  tests/test_regression_memcmp_definite_size.py
Labels: bug, refactor

#904 cfg fast: fix double add for zero segment
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#909 engine.successors(): test if assembling succeeds
  angr/engines/hub.py
Labels: enhancement

#911 Fix the spiller test case for Appveyor.
  tests/test_spiller.py
Labels: bug

#808 Control Flow Blanket
  angr/analyses/cfg/__init__.py
  angr/analyses/cfg/cfb.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/memory_data.py
  angr/analyses/disassembly.py
  tests/test_cfgfast.py
Labels: feature

#888 Extensive refactoring and clean-up of the SimulationManager code
  angr/__init__.py
  angr/analyses/congruency_check.py
  angr/analyses/identifier/functions/fdprintf.py
  angr/analyses/identifier/functions/printf.py
  angr/analyses/identifier/functions/snprintf.py
  angr/analyses/identifier/functions/sprintf.py
  angr/analyses/veritesting.py
  angr/callable.py
  angr/exploration_techniques/__init__.py
  angr/exploration_techniques/cacher.py
  angr/exploration_techniques/crash_monitor.py
  angr/exploration_techniques/dfs.py
  angr/exploration_techniques/director.py
  angr/exploration_techniques/driller_core.py
  angr/exploration_techniques/explorer.py
  angr/exploration_techniques/lengthlimiter.py
  angr/exploration_techniques/loop_seer.py
  angr/exploration_techniques/looplimiter.py
  angr/exploration_techniques/manual_mergepoint.py
  angr/exploration_techniques/oppologist.py
  angr/exploration_techniques/spiller.py
  angr/exploration_techniques/tech_builder.py
  angr/exploration_techniques/threading.py
  angr/exploration_techniques/tracer.py
  angr/exploration_techniques/veritesting.py
  angr/factory.py
  angr/manager.py
  angr/misc/__init__.py
  angr/misc/hookset.py
  angr/misc/immutability.py
  angr/project.py
  angr/sim_manager.py
  angr/surveyors/surveyor.py
  tests/manual_explosion.py
  tests/manual_performance.py
  tests/test_0div.py
  tests/test_accuracy.py
  tests/test_checkbyte.py
  tests/test_echo.py
  tests/test_fauxware.py
  tests/test_hookset.py
  tests/test_immutability.py
  tests/test_inspect.py
  tests/test_simulation_manager.py
  tests/test_unicorn.py
Labels: enhancement
