Repository angr/angr, pull requests merged in 2018-10, with the labels that each got.

#1223 CFGFast: Fix a stupid bug. Close #1221.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1225 Labels: Skip TYPE_OTHER symbols by defualt.
  angr/knowledge_plugins/labels.py
Labels: bug

#1224 CFGFast: Fix the issue with string identification.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/reassembler.py
  tests/test_cfgemulated.py
  tests/test_cfgfast.py
Labels: bug

#1229 CFGFast: Fix a bug that may cause missing jumpout sites.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1243 CCall: Correctly truncate operands in 32-bit mode of AArch64.
  angr/engines/vex/ccall.py
  tests/test_vex.py
Labels: bug

#1244 Fix minor configuration setup for self modifying code option
  angr/project.py
Labels: bug

#1246 Implement a simple code tagging analysis.
  angr/analyses/__init__.py
  angr/analyses/code_tagging.py
  angr/knowledge_plugins/functions/function.py
  tests/test_codetagging.py
Labels: feature

#1257 Add indirect call handlers to Reaching Definitions
  angr/analyses/reaching_definitions/engine_vex.py
Labels: enhancement

#1262 VariableRecoveryFast: Fix an exception when ProcessorState.bp is None. Closes #1259.
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: bug

#1263 Fix an exception thrown upon unsupported VEX unops. Closes #1260.
  angr/engines/light/engine.py
Labels: bug

#1267 VariableRecovery: Only insert states with concrete IPs. Closes #1264.
  angr/analyses/variable_recovery/variable_recovery.py
Labels: bug

#1268 CFGFast: Double-check to_outside when applying transition edges. Closes #1266.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1272 Call set_state() on socket pairs.
  angr/state_plugins/posix.py
Labels: bug

#1274 memcpy: Make sure the conditional size *never* goes beyond the limit.
  angr/procedures/libc/memcpy.py
Labels: enhancement

#1258 Fix FormatString.interpret expecting component to be str
  angr/procedures/stubs/format_parser.py
Labels: bug, tests

#1233 Added MEMORY_CHUNK_INDIVIDUAL_READS option
  angr/procedures/libc/strchr.py
  angr/procedures/libc/strlen.py
  angr/procedures/libc/strstr.py
  angr/sim_options.py
  angr/state_plugins/abstract_memory.py
  angr/state_plugins/fast_memory.py
  angr/state_plugins/symbolic_memory.py
  angr/storage/memory.py
Labels: enhancement
