Repository angr/angr, pull requests merged in 2018-06, with the labels that each got.

#1022 Skip some tests for AppVeyor.
  tests/test_memory.py
  tests/test_tracer.py
Labels: enhancement

#1024 Catch SimSolverModeError in eval_one() when a default value is provided.
  angr/state_plugins/solver.py
Labels: bug

#1025 Disassembly: Correctly render RIP-relative addressing operands.
  angr/analyses/disassembly.py
Labels: feature

#1040 catching StopIteration exception
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1043 CFGAccurate: Fix a bug where a block without successors is not added into the function correctly.
  angr/analyses/cfg/cfg_accurate.py
  angr/knowledge_plugins/functions/function.py
Labels: bug

#1047 Better handling of mips branching - fixes issue that came up in Issue #1045
  angr/exploration_techniques/explorer.py
Labels: enhancement

#1050 CFGFast: Check the jumpkind of the state before passing it to factory.syscall(). Closes #971.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1053 CFGFast: Speed up next_pos_with_sort_not_in() on large binaries.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1066 Recognize options with number
  angr/sim_options.py
Labels: bug

#1069 Lifter: Fix the crash caused by lifting a block with unfilled holes in memory under fastpath mode. Closes #1062.
  angr/engines/vex/engine.py
Labels: bug

#1061 handling tmp chaining in find_consumers like in find_sources
  angr/analyses/ddg.py
Labels: feature

#1080 JumpTableResolver now supports resolving ARM jump tables.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/engines/vex/statements/loadg.py
  angr/slicer.py
  angr/state_plugins/abstract_memory.py
  angr/state_plugins/inspect.py
  angr/state_plugins/symbolic_memory.py
  angr/storage/memory.py
  tests/test_cfgfast.py
Labels: feature

#1081 Reduce the memory footprint of CFGFast - Step A
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_node.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/test_cfgfast.py
Labels: enhancement, refactor

#1083 JumpTableResolver: Load jump targets from C-backed memory directly.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: enhancement

#1086 Adding an init $t9 for ReachingDefinitionAnalysis with MIPS.
  angr/analyses/reaching_definitions/reaching_definitions.py
Labels: bug

#1091 Fix a crash caused by CFGNodes without sizes in get_all_nodes().
  angr/analyses/cfg/cfg_base.py
Labels: bug

#1093 Fix List Out of Range in Loop Seer
  angr/exploration_techniques/loop_seer.py
Labels: bug
