Repository angr/angr, pull requests merged in 2018-09, with the labels that each got.

#1204 Fix state attribute typo
  angr/calling_conventions.py
Labels: bug

#1193 Warn about missing register/memory reads.
  angr/state_plugins/symbolic_memory.py
Labels: enhancement

#1208 Fix an issue that may lead to an excessive memory usage in Tracer.
  angr/procedures/tracer/random.py
Labels: enhancement

#1219 Rename CFGAccurate to CFGEmulated (Do not lie to the users) + bonus
  angr/analyses/__init__.py
  angr/analyses/binary_optimizer.py
  angr/analyses/bindiff.py
  angr/analyses/cdg.py
  angr/analyses/cfg/__init__.py
  angr/analyses/cfg/cfg.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_node.py
  angr/analyses/reassembler.py
  angr/analyses/veritesting.py
  angr/analyses/vfg.py
  angr/blade.py
  angr/exploration_techniques/director.py
  angr/knowledge_plugins/functions/function.py
  angr/project.py
  tests/broken_simcc.py
  tests/broken_slicing.py
  tests/manual_performance.py
  tests/test_cdg.py
  tests/test_cfgaccurate.py
  tests/test_ddg.py
  tests/test_function_manager.py
  tests/test_serialization.py
  tests/test_simulation_manager.py
  tests/test_vfg.py
Labels: refactor

#1200 The ARM CFG Party: Numerous correctness fixes regarding ARM and conditional execution
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/engines/vex/engine.py
Labels: enhancement
