Repository angr/angr, pull requests merged in 2018-07, with the labels that each got.

#1097 JumpTableResolver: Handle a non-jumptable case in ARM. Closes #1090.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#1099 Add ARM edges to CFGFast cfg_switches
  tests/test_cfgfast.py
Labels: bug

#1063 Implement indirect jumps resolving for CFGAccurate
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/indirect_jump_resolvers/x86_elf_pic_plt.py
  angr/blade.py
  tests/test_cfgaccurate.py
Labels: feature

#1101 Remove redundant assignment from CFGAccurate copy
  angr/analyses/cfg/cfg_accurate.py
Labels: bug

#1100 CFGFast's _create_job doesn't need fast_indirect_jump_resolution
  angr/analyses/cfg/cfg_fast.py
Labels: refactor

#1105 VFG: Fix some minor bugs. Closes #1077.
  angr/analyses/vfg.py
  tests/test_vfg_path.py
Labels: bug

#1109 Display PyPI statistics in README.md.
  README.md
Labels: refactor

#1112 Added another version of libc.so
  angr/procedures/definitions/glibc.py
Labels: enhancement

#1103 CFG indirect jump resolution refactor
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgaccurate.py
Labels: refactor

#1113 Fix CFGFast: NetworkXError: Node not in digraph (#1107)
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1110 Mark 2 existing indirect jump resolving techniques as deprecated
  angr/analyses/cfg/cfg_accurate.py
Labels: enhancement

#1130 CFG: Clean up the indirect jump resolving code.
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: refactor

#1142 Fix sortedcontainers API
  angr/analyses/cfg/cfg_fast.py
  angr/keyed_region.py
  angr/knowledge_plugins/functions/function_manager.py
  angr/storage/paged_memory.py
  requirements.txt
  setup.py
Labels: refactor

#1092 Many improvements to make CFGFast fast again.
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_node.py
  angr/block.py
  angr/codenode.py
  angr/engines/vex/engine.py
  angr/factory.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
  native/sim_unicorn.cpp
  tests/test_cfgfast.py
Labels: enhancement, refactor
