Repository angr/angr, pull requests merged in 2018-04, with the labels that each got.

#927 ForwardAnalysis: Store job_info to self._job_map regardless.
  angr/analyses/forward_analysis.py
Labels: bug

#928 ForwardAnalysis: Add a has_job() method.
  angr/analyses/forward_analysis.py
Labels: feature

#930 CFGFast: Fix a wrong assignment in _analyze_all_function_features()
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#931 CFGFast: Call _add_returning_function() when needed.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#937 setup.py: fix version for capstone
  setup.py
Labels: bug

#935 Function: Determine whether it is a syscall or not if 'syscall' is not provided.
  angr/knowledge_plugins/functions/function.py
Labels: bug

#929 _analyse_function_features(): Skip empty functions.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#925 Add prototypes and MS 64-bit CC
  angr/calling_conventions.py
  angr/procedures/advapi32/__init__.py
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/advapi32.py
  angr/procedures/definitions/kernel32.py
  angr/procedures/definitions/msvcr.py
  angr/procedures/stubs/ReturnUnconstrained.py
  angr/procedures/win32/InterlockedExchange.py
Labels: enhancement

#932 CFGFast: Special handling of calls targeting the next instruction.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#941 SimLibrary: Allow adding C-style declarations.
  angr/procedures/definitions/__init__.py
Labels: feature

#945 Calculating ccalls should only raise SimErrors, not other exceptions.
  angr/engines/vex/ccall.py
Labels: bug

#924 Add wchar and case-sensitivity support for string-related SimProcedures
  angr/procedures/definitions/kernel32.py
  angr/procedures/libc/strcmp.py
  angr/procedures/libc/strlen.py
  angr/procedures/libc/strncmp.py
  angr/procedures/libc/wchar.py
  angr/procedures/posix/strcasecmp.py
  tests/test_strcasecmp.py
Labels: feature

#944 Do not fail state stepping if we cannot solve the return address.
  angr/engines/successors.py
  angr/simos/simos.py
Labels: bug

#959 Typo fix in sim_manager.py: resilence -> resilience.
  angr/sim_manager.py
Labels: bug

#943 SimSolver: Do not return a symbolic solver if SYMBOLIC is absent from state options.
  angr/analyses/cfg/cfg_accurate.py
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  angr/engines/successors.py
  angr/state_plugins/solver.py
Labels: bug

#942 Add function prototypes for glibc.
  angr/calling_conventions.py
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/glibc.py
  angr/procedures/libc/printf.py
  angr/procedures/libc/snprintf.py
  angr/procedures/libc/sprintf.py
  angr/procedures/posix/bind.py
  angr/procedures/posix/open.py
  angr/procedures/posix/recv.py
  angr/procedures/posix/send.py
  angr/sim_procedure.py
Labels: feature

#953 A faster method to evaluate symbolic targets coming from jump tables.
  angr/engines/successors.py
  angr/state_plugins/__init__.py
  angr/state_plugins/configuration.py
  angr/state_plugins/symbolic_memory.py
  angr/storage/memory.py
Labels: enhancement

#963 Typo fix in sim_options.py.
  angr/sim_options.py
Labels: bug

#918 Try to fix a bug in ARM lr tracking
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#958 Add util methods for converting C declarations to Python representations.
  angr/sim_type.py
  angr/utils/library.py
  tests/test_types.py
Labels: feature

#964 Implement SimStateOptions. Closes #877.
  angr/analyses/identifier/runner.py
  angr/engines/successors.py
  angr/errors.py
  angr/exploration_techniques/oppologist.py
  angr/sim_options.py
  angr/sim_state.py
  angr/sim_state_options.py
  angr/state_plugins/__init__.py
  angr/state_plugins/configuration.py
  angr/state_plugins/symbolic_memory.py
Labels: feature

#970 Set function name to the name passed as parameter
  angr/knowledge_plugins/functions/function_manager.py
Labels: bug
