Repository angr/angr, pull requests merged in 2018-05, with the labels that each got.

#976 CFGFast: Convert Thumb addrs to real offsets before checking traced_addresses
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#985 Fix SimState.jumpkind.
  angr/sim_state.py
Labels: bug

#984 SimStateOptions: Do not raise exceptions upon calling dir().
  angr/sim_state_options.py
Labels: bug

#983 CFGFast: Fill in the jump_tables dict.
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#1007 Exception was missing a raise
  angr/analyses/identifier/identify.py
Labels: bug

#1003 Specify Python 2 and IPython 5.x LTS in README.md
  README.md
Labels: enhancement

#1006 Fix several cases of undefined names. Closes #1002.
  angr/analyses/cfg/indirect_jump_resolvers/resolver.py
  angr/procedures/linux_loader/__tls_get_addr.py
  angr/storage/paged_memory.py
  tests/broken_FindAvoidConflict.py
  tests/test_file_struct_funcs.py
  tests/test_signed_div.py
Labels: bug

#1015 Fixed when `bound_reached` callback is triggered
  angr/exploration_techniques/loop_seer.py
Labels: bug

#1017 CFGFast: New code blocks should not overlap with an recognized data item.
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#1018 Callgraph: Add orphan functions to the call graph.
  angr/knowledge_plugins/functions/function_manager.py
Labels: bug
