Repository angr/angr, pull requests merged in 2018-12, with the labels that each got.

#1302 Support jumptable on GCC+S390X. Closes #1289.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/blade.py
  angr/slicer.py
  angr/state_plugins/abstract_memory.py
Labels: enhancement

#1315 Merge leading blocks of a function if the second one is abnormal. Closes #1312.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_node.py
Labels: enhancement

#1325 prevent local_runtime_values from tracing unreachable blocks
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#1328 Enhance indirect call handling behavior in reaching definitions
  angr/analyses/reaching_definitions/engine_vex.py
Labels: feature

#1330 Fix several bugs in Reassembler
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/reassembler.py
  tests/test_reassembler.py
Labels: bug

#1332 Split UnresolvableTarget into UnresolvableJumptarget and UnresolvableCallTarget
  angr/analyses/binary_optimizer.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_node.py
  angr/codenode.py
  angr/engines/successors.py
  angr/procedures/procedure_dict.py
  angr/procedures/stubs/UnresolvableCallTarget.py
  angr/procedures/stubs/UnresolvableJumpTarget.py
  angr/procedures/stubs/UnresolvableTarget.py
  angr/simos/simos.py
  tests/test_cfgfast.py
Labels: bug

#1335 CFGBase: Skip all hooks and syscalls when merging nodes.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#1336 CFGFast: Resolve indirect jumps before scanning function prologues.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1339 use solver instead of (deprecated) se
  angr/analyses/cfg/cfg_emulated.py
Labels: refactor

#1337 JumpTableResolver: Resolve load-signext-addbase jump tables.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/exploration_techniques/loop_seer.py
  tests/test_str_funcs.py
Labels: feature

#1340 SimStateOptions: Speed up one_type().
  angr/sim_state_options.py
Labels: enhancement

#1342 SimIRExpr: Do not call state.add_constraints() if there are no constraints to add.
  angr/engines/vex/expressions/base.py
Labels: enhancement

#1341 CFGFast: Skip jobs that are outside predefined regions.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1343 Speed up jump table resolving.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/blade.py
Labels: enhancement

#1344 Add an option 'force_fastpath' to CFG.get_any_node(). Speed up CFGFast.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1345 Convert SimIRExpr and SimIRStmt classes to Python 3 style. Add slots.
  angr/engines/vex/expressions/base.py
  angr/engines/vex/expressions/ccall.py
  angr/engines/vex/expressions/const.py
  angr/engines/vex/expressions/get.py
  angr/engines/vex/expressions/geti.py
  angr/engines/vex/expressions/gsptr.py
  angr/engines/vex/expressions/ite.py
  angr/engines/vex/expressions/load.py
  angr/engines/vex/expressions/op.py
  angr/engines/vex/expressions/rdtmp.py
  angr/engines/vex/expressions/unsupported.py
  angr/engines/vex/expressions/vecret.py
  angr/engines/vex/statements/abihint.py
  angr/engines/vex/statements/base.py
  angr/engines/vex/statements/cas.py
  angr/engines/vex/statements/dirty.py
  angr/engines/vex/statements/exit.py
  angr/engines/vex/statements/imark.py
  angr/engines/vex/statements/llsc.py
  angr/engines/vex/statements/loadg.py
  angr/engines/vex/statements/mbe.py
  angr/engines/vex/statements/noop.py
  angr/engines/vex/statements/put.py
  angr/engines/vex/statements/puti.py
  angr/engines/vex/statements/store.py
  angr/engines/vex/statements/storeg.py
  angr/engines/vex/statements/wrtmp.py
Labels: refactor

#1346 A more Pythonic way of dict read.
  angr/knowledge_plugins/functions/function_manager.py
Labels: refactor

#1356 CFBlanket: Support enumerating regions.
  angr/analyses/cfg/cfb.py
Labels: feature

#1357 Support running CPU-bound analyses without pegging the Python interpreter.
  angr/analyses/analysis.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#1359 Correctly reason about where phi variables are.
  angr/analyses/__init__.py
  angr/analyses/dominance_frontier.py
  angr/analyses/variable_recovery/variable_recovery.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/keyed_region.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/sim_variable.py
  angr/utils/graph.py
  tests/test_variablerecovery.py
Labels: feature

#1362 Introduce SYMBOL_FILL_* state options, add to unsavory situations
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/sim_options.py
  angr/simos/simos.py
  angr/state_plugins/symbolic_memory.py
Labels: enhancement
