Repository angr/angr, pull requests merged in 2018-11, with the labels that each got.

#1288 Fix Keystone for ARM THUMB mode. Add a test case for it.
  angr/engines/vex/engine.py
  tests/test_keystone.py
Labels: bug

#1283 Initialize _security_cookie in SimWindows
  angr/simos/windows.py
  tests/test_accuracy.py
  tests/test_windows_stack_cookie.py
Labels: feature

#1297 Rename: CFGNodeA->CFGENode
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_node.py
Labels: enhancement

#1299 CFGFast: support thunks
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  angr/engines/vex/engine.py
  angr/exploration_techniques/explorer.py
  angr/factory.py
Labels: enhancement

#1048 Symbion: Synchronized Concrete and Symbolic Execution for Complex Environments
  angr/analyses/cfg/cfb.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/x86_elf_pic_plt.py
  angr/engines/__init__.py
  angr/engines/concrete.py
  angr/engines/unicorn.py
  angr/engines/vex/ccall.py
  angr/engines/vex/dirty.py
  angr/engines/vex/engine.py
  angr/engines/vex/statements/dirty.py
  angr/errors.py
  angr/exploration_techniques/__init__.py
  angr/exploration_techniques/symbion.py
  angr/project.py
  angr/sim_options.py
  angr/simos/linux.py
  angr/simos/simos.py
  angr/simos/windows.py
  angr/state_plugins/__init__.py
  angr/state_plugins/concrete.py
  angr/state_plugins/symbolic_memory.py
  angr/state_plugins/unicorn_engine.py
  angr/storage/memory.py
  angr/storage/paged_memory.py
  tests/manual_concrete_not_packed_pe32.py
  tests/manual_concrete_not_packed_pe64.py
  tests/manual_concrete_packed_pe32.py
  tests/test_concrete_not_packed_elf32.py
  tests/test_concrete_not_packed_elf64.py
  tests/test_concrete_packed_elf32.py
  tests/test_concrete_packed_elf64.py
Labels: feature

#1300 Fix a bug in CFG/Function normalization.
  angr/analyses/cfg/cfg_base.py
  angr/knowledge_plugins/functions/function.py
Labels: bug

#1301 Implement tail-call optimization detection. Closes #1286.
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/stack_pointer_tracker.py
  angr/knowledge_plugins/functions/function.py
  tests/test_cfgfast.py
Labels: feature

#1303 Unpin cachetools. Sync https://github.com/angr/claripy/pull/116.
  setup.py
Labels: refactor

#1284 SimAbstractMemory: improve precision with which the address is concretized
  angr/sim_options.py
  angr/state_plugins/abstract_memory.py
  angr/state_plugins/solver.py
Labels: enhancement

#1309 Set state again for SimFiles in socketqueue before using.
  angr/state_plugins/posix.py
Labels: bug

#1308 Add a simple proc FS implementation.
  angr/state_plugins/posix.py
Labels: feature

#1307 Fix mountpoint resolution by matching deeper paths first.
  angr/state_plugins/filesystem.py
Labels: bug

#1310 Fix SimSymbolicMemory._find() in tracing mode.
  angr/sim_options.py
  angr/state_plugins/symbolic_memory.py
Labels: bug

#1314 CFGFast: Improve resiliency when enumerating block statements.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1313 CFGFast: Avoid generating blocks that go across function boundaries.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
Labels: bug
