Repository angr/angr, pull requests merged in 2019-04, with the labels that each got.

#1494 Fix for incorrect block.size during CFG normalilzation for ARM arch
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_fast_soot.py
  angr/knowledge_plugins/functions/function.py
Labels: bug

#1499 Fix for incorrect condition to filter out ARM plt entries
  angr/analyses/cfg/cfg_base.py
Labels: bug

#1501 Make SP tracker take block sizes from CFG
  angr/analyses/stack_pointer_tracker.py
Labels: enhancement

#1504 SimAbstractMemory: _load() should not return None upon address concretization failures.
  angr/state_plugins/abstract_memory.py
Labels: bug

#1503 Implement necessary helpers and information storage for call pretty printing
  angr/calling_conventions.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
  angr/sim_type.py
Labels: enhancement

#1507 When the tracer finds a crash it does not change the predecessors whi…
  angr/exploration_techniques/tracer.py
Labels: bug

#1457 Add optimization pass to remove bp stores and restores
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  tests/test_bp_save_optimization.py
Labels: feature

#1508 Rename FP rounding modes.
  angr/calling_conventions.py
  angr/engines/vex/irop.py
Labels: refactor

#1506 KnowledgeBase v2
  angr/analyses/backward_slice.py
  angr/analyses/binary_optimizer.py
  angr/analyses/cfg/__init__.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_fast_soot.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
  angr/analyses/cfg/memory_data.py
  angr/analyses/cfg/segment_list.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/reassembler.py
  angr/analyses/veritesting.py
  angr/annocfg.py
  angr/blade.py
  angr/block.py
  angr/engines/vex/engine.py
  angr/exploration_techniques/director.py
  angr/exploration_techniques/loop_seer.py
  angr/knowledge_base/__init__.py
  angr/knowledge_base/knowledge_base.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/cfg/__init__.py
  angr/knowledge_plugins/cfg/cfg_manager.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/cfg_node.py
  angr/knowledge_plugins/cfg/indirect_jump.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/plugin.py
  angr/project.py
  angr/protos/__init__.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  angr/serializable.py
  angr/utils/__init__.py
  angr/utils/constants.py
  angr/utils/enums_conv.py
  setup.py
  tests/test_cdg.py
  tests/test_cfgemulated.py
  tests/test_cfgfast.py
  tests/test_function.py
  tests/test_function_manager.py
  tests/test_reachingdefinitions.py
  tests/test_serialization.py
  tests/test_slicing.py
  tests/test_variablerecovery.py
Labels: feature

#1511 SimSystemPosix: Call set_state() on self.sockets.
  angr/state_plugins/posix.py
Labels: bug

#1510 Fix the __repr__() method of FormatString.
  angr/procedures/stubs/format_parser.py
Labels: enhancement

#1525 strtol: Correctly convert 11-digit numbers.
  angr/procedures/libc/strtol.py
  tests/test_strtol.py
Labels: bug

#1526 SimLinux: Make sure stack canary starts with a null byte.
  angr/simos/linux.py
Labels: enhancement

#1527 FormatParser: Support .* (dynamic field width).
  angr/procedures/stubs/format_parser.py
Labels: feature

#1530 Fix a panic in libvex caused by passing wrong values to typeOfPrimop().
  angr/engines/vex/expressions/op.py
Labels: bug

#1531 Fix proto message enum reference
  angr/knowledge_plugins/cfg/memory_data.py
Labels: bug

#1539 SimSystemPosix.open: Take string names without crashing.
  angr/state_plugins/posix.py
Labels: bug

#1538 Remove the redundant Reverse() operation in uninitialized ASTs read from files.
  angr/state_plugins/preconstrainer.py
  angr/state_plugins/symbolic_memory.py
  tests/test_files.py
Labels: bug

#1545 Unicorn: Always re-create the uc object on MIPS32.
  angr/state_plugins/unicorn_engine.py
Labels: bug

#1546 Add a new state option MEMORY_FIND_STRICT_SIZE_LIMIT.
  angr/sim_options.py
  angr/state_plugins/symbolic_memory.py
Labels: enhancement

#1543 Tracer: Add a permissive mode.
  angr/exploration_techniques/tracer.py
Labels: feature

#1547 CFG: Resolve 'call [rip+xxx]' style indirect calls in x86-64 ELFs.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/indirect_jump_resolvers/__init__.py
  angr/analyses/cfg/indirect_jump_resolvers/amd64_elf_got.py
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
  angr/analyses/cfg/indirect_jump_resolvers/resolver.py
Labels: feature

#1548 SimProcedure.static_exits: Allow providing name hints.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/labels.py
  angr/procedures/glibc/__libc_start_main.py
  angr/procedures/posix/pthread.py
  angr/sim_procedure.py
Labels: enhancement

#1549 Create an artificial label for the entry point of the main object.
  angr/knowledge_plugins/labels.py
Labels: enhancement
