Repository angr/angr, pull requests merged in 2019-09, with the labels that each got.

#1700 Bug fix: DDG: SimMemoryVariable with negative address
  angr/analyses/ddg.py
  tests/test_ddg_memvar_addresses.py
Labels: bug

#1708 Refactoring `ForwardAnalysis`
  angr/analyses/forward_analysis/__init__.py
  angr/analyses/forward_analysis/job_info.py
  angr/analyses/forward_analysis/visitors/__init__.py
  angr/analyses/forward_analysis/visitors/call_graph.py
  angr/analyses/forward_analysis/visitors/function_graph.py
  angr/analyses/forward_analysis/visitors/graph.py
  angr/analyses/forward_analysis/visitors/loop.py
  angr/analyses/forward_analysis/visitors/single_node_graph.py
Labels: refactor

#1717 Fix the unicorn_pickle error on CI.
  tests/test_cfgemulated.py
Labels: bug

#1705 Cleaning `AnnotatedCFG`
  angr/annocfg.py
  angr/exploration_techniques/slicecutor.py
Labels: enhancement

#1724 Function: Clarify ._addr_to_block_node in comments. Closes #1710.
  angr/knowledge_plugins/functions/function.py
Labels: refactor

#1725 Support for explicit text modes "rt" and "wt" in fopen
  angr/procedures/libc/fopen.py
Labels: enhancement

#1731 ReachingDefinitions: Create external defs upon undefined register reads.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug

#1732 ReachingDefinitions: Propagate uses through tmps.
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/reaching_definitions.py
Labels: enhancement

#1736 Check edge' size before using its value
  angr/knowledge_plugins/functions/function.py
Labels: bug
