Repository angr/angr, pull requests merged in 2019-11, with the labels that each got.

#1751 Cleaning
  angr/analyses/forward_analysis/__init__.py
  angr/analyses/reaching_definitions/engine_vex.py
  tests/test_function_manager.py
  tests/test_reachingdefinitions.py
Labels: refactor

#1780 CFGEmulated: Fix a crash when the call target is unknown. Close #1772.
  angr/analyses/cfg/cfg_emulated.py
  angr/knowledge_plugins/functions/function_manager.py
Labels: bug

#1785 Reassembler: Fix a bug with memory operand formatting in Intel syntax.
  angr/analyses/reassembler.py
Labels: bug

#1784 Add arithmetic simplification
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
Labels: enhancement

#1757 RDA visited nodes
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/engines/light/engine.py
  tests/reachingdefinitions_results/x86_64/all_definitions.pickle
  tests/reachingdefinitions_results/x86_64/all_visited_blocks.pickle
  tests/reachingdefinitions_results/x86_64/fauxware_definitions.pickle
  tests/reachingdefinitions_results/x86_64/fauxware_visited_blocks.pickle
  tests/reachingdefinitions_results/x86_64/loop_definitions.pickle
  tests/reachingdefinitions_results/x86_64/loop_visited_blocks.pickle
  tests/test_reachingdefinitions.py
Labels: enhancement

#1833 Do not raise exceptions for unsupported syscalls. Fix #1799.
  angr/engines/successors.py
  angr/simos/linux.py
  tests/test_state.py
Labels: bug

#1834 Fix docstring for SimState.
  angr/sim_state.py
Labels: refactor

#1835 Add a new state option BYPASS_ERRORED_IRSTMT. Fix #1800.
  angr/engines/vex/engine.py
  angr/sim_options.py
  tests/test_state.py
Labels: enhancement

#1837 CFGFast: Indirect jumps may go outside the current function.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: bug

#1838 SimSymbolicMemory._fill_missing(): Do not crash when ip is symbolic.
  angr/state_plugins/symbolic_memory.py
Labels: bug

#1839 OptimizationEngine: Respect _process() in the base Mixin.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
Labels: bug

#1842 JumpTableResolver: Ensure THUMB mode code jumps to THUMB mode targets.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#1703 Check for ENOENT in the unlink SimProcedure
  angr/procedures/linux_kernel/unlink.py
  tests/test_unlink.py
Labels: enhancement

#1849 Rda clean engine
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/engines/light/engine.py
Labels: refactor

#1843 CFGFast: Add a new heuristic to decide THUMB mode during complete scans.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#1853 LightEngineVEX: Do not assume function addrs can always be determined. Closes #1850.
  angr/engines/light/engine.py
Labels: bug

#1854 CFGFast: Resolve indirect jumps before following undetermined pending jobs.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#1840 Cleaning
  angr/analyses/__init__.py
  angr/analyses/reaching_definitions/__init__.py
  angr/analyses/reaching_definitions/def_use.py
  angr/analyses/reaching_definitions/live_definitions.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/test_reachingdefinitions.py
Labels: refactor

#1855 BasePointerSaveSimplifier: Fix amd64 support.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  tests/test_baseptr_save_simplifier.py
  tests/test_bp_save_optimization.py
Labels: bug
