Repository angr/angr, pull requests merged in 2019-03, with the labels that each got.

#1467 Add extended VEX support to the decompiler
  angr/engines/vex/irop.py
Labels: enhancement

#1462 Fix create in FunctionManager.function().
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function_manager.py
  tests/test_cfgfast.py
Labels: bug

#1234 ARM CFG party favor: Cortex-M support and CFG fixes
  angr/analyses/boyscout.py
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_arch_options.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/vfg.py
  angr/calling_conventions.py
  angr/engines/vex/ccall.py
  angr/project.py
  angr/state_plugins/view.py
  angr/storage/memory.py
  tests/test_cfg_thumb_firmware.py
  tests/test_cfgemulated.py
  tests/test_cfgfast.py
  tests/test_decompiler.py
Labels: enhancement, feature
