Repository angr/angr, pull requests merged in 2019-06, with the labels that each got.

#1596 More tests for reassembler
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  tests/test_reassembler.py
Labels: bug, enhancement

#1591 Various improvements to CFG {de}serialization
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/cfg_node.py
  tests/test_cfgfast.py
Labels: bug

#1597 Enhance the jump table resolver and add test cases.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/engines/light/data.py
  angr/engines/light/engine.py
  tests/test_cfg_thumb_firmware.py
  tests/test_cfgfast.py
  tests/test_jumptables.py
Labels: enhancement, refactor

#1594 Tests for Reachingdefinitions analysis
  tests/reachingdefinitions_results/x86_64/all.pickle
  tests/reachingdefinitions_results/x86_64/fauxware.pickle
  tests/reachingdefinitions_results/x86_64/loop.pickle
  tests/test_reachingdefinitions.py
Labels: enhancement

#1602 minor bug fix in sim_type, simprocedures for pread64 and pwrite64
  angr/procedures/definitions/linux_kernel.py
  angr/procedures/posix/pread64.py
  angr/procedures/posix/pwrite64.py
  angr/sim_type.py
  tests/test_pwrite_pread.py
  tests/test_string.py
Labels: bug

#1565 Concrete memory backing, unicorn page caching fix
  angr/state_plugins/symbolic_memory.py
  angr/state_plugins/unicorn_engine.py
  angr/storage/memory_object.py
  angr/storage/paged_memory.py
  native/sim_unicorn.cpp
  tests/test_strtol.py
Labels: enhancement

#1616 Fix some test path joins
  tests/test_accuracy.py
  tests/test_windows_args.py
  tests/test_windows_stack_cookie.py
Labels: refactor

#1615 Bug fix: CFG.get_any_node() fails to get 0-length nodes when anyaddr is True
  angr/knowledge_plugins/cfg/cfg_model.py
  tests/test_cfg_get_any_node.py
Labels: bug

#1621 Convert VEX light engine and AIL light engine to mixins.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/engines/light/__init__.py
  angr/engines/light/engine.py
Labels: refactor

#1624 add handlers for AIL engine
  angr/analyses/reaching_definitions/dataset.py
  angr/engines/light/engine.py
Labels: enhancement

#1352 Propagator (mostly-constant propagation) + XRefs analysis
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/propagator/__init__.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/engine_base.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/values.py
  angr/analyses/propagator/vex_vars.py
  angr/analyses/reaching_definitions/dataset.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reassembler.py
  angr/analyses/xrefs.py
  angr/engines/light/engine.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/cfg/__init__.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/knowledge_plugins/xrefs/__init__.py
  angr/knowledge_plugins/xrefs/xref.py
  angr/knowledge_plugins/xrefs/xref_manager.py
  angr/knowledge_plugins/xrefs/xref_types.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  angr/protos/xrefs.proto
  angr/protos/xrefs_pb2.py
  tests/test_constantpropagation.py
  tests/test_xrefs.py
Labels: feature

#1629 Propagator: Return TOP for uninitialized variables.
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/values.py
  angr/analyses/propagator/vex_vars.py
Labels: bug

#1631 The ARM XRefs Party? Making XRefs useable in angr
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/values.py
  angr/analyses/reassembler.py
  angr/analyses/xrefs.py
  angr/engines/light/engine.py
  angr/knowledge_plugins/cfg/cfg_node.py
  tests/test_cfgfast.py
  tests/test_constantpropagation.py
  tests/test_decompiler.py
  tests/test_structurer.py
  tests/test_xrefs.py
Labels: enhancement

#1632 Reassembler: Raise an exception on an unexpected path to avoid undefined variable exceptions in rare cases.
  angr/analyses/reassembler.py
Labels: bug
