Repository angr/angr, pull requests merged in 2019-10, with the labels that each got.

#1661 Add a pointer symbolization plugin
  angr/engines/successors.py
  angr/project.py
  angr/sim_state.py
  angr/state_plugins/__init__.py
  angr/state_plugins/concrete.py
  angr/state_plugins/inspect.py
  angr/state_plugins/symbolizer.py
  angr/storage/paged_memory.py
  tests/test_symbolization.py
Labels: feature

#1739 Fix symbolic operand relocation logging.
  angr/analyses/reassembler.py
Labels: bug

#1759 Function: Support obtaining the instruction address for any address.
  angr/knowledge_plugins/functions/function.py
  tests/test_function.py
Labels: feature

#1760 CFBlanket: Do not assume sizes of pseudo regions are 80 bytes.
  angr/analyses/cfg/cfb.py
Labels: bug

#1761 VariableRecoveryFast: Do not crash if cc.sp_delta is None.
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: bug

#1762 Analysis: Remove self._progressbar after analysis to support pickling.
  angr/analyses/analysis.py
Labels: bug

#1764 Fix keyError on CFGEmualted
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#1765 Fix format printing for non-address targets
  angr/knowledge_plugins/xrefs/xref.py
Labels: bug

#1750 knowledge_plugins.functions.Function: reorganise
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_parser.py
Labels: refactor

#1777 CFGFast: Allow executing blocks with resilience. Close #1696.
  angr/analyses/cfg/cfg_fast.py
Labels: bug
