Repository angr/angr, pull requests merged in 2019-07, with the labels that each got.

#1635 calloc: set final_size correctly
  angr/state_plugins/heap/heap_brk.py
Labels: bug

#1640 CFGEmulated: Create a fake-ret successor if the indirect jump is a call.
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#1643 `LiveDefinitions` does not need a loader
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/test_reachingdefinitions.py
Labels: refactor

#1606 Implement Azure CI
  azure-pipelines.yml
Labels: feature

#1658 Add preliminary support for BinSync.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/patches.py
  angr/knowledge_plugins/sync/__init__.py
  angr/knowledge_plugins/sync/sync_manager.py
  tests/test_cfgfast.py
Labels: feature

#1647 `get_sp` method for `LiveDefinitions`
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/test_reachingdefinitions.py
Labels: feature

#1642 Correct `insn_observe` and `node_observe`
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/test_reachingdefinitions.py
Labels: bug

#1664 JumptableResolver: Multiple fixes to address an OOM issue.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/blade.py
Labels: bug

#1666 Do not filter THUMB successors if they are obviously legit.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/blade.py
Labels: enhancement

#1669 Remove broken dependency
  setup.py
Labels: dependency

#1670 add project.filename as part of cfg_key for cfg_cache
  angr/analyses/veritesting.py
Labels: bug

#1675 CFGFast: Occupy jump tables. Closes #1671.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/knowledge_plugins/cfg/indirect_jump.py
  tests/test_jumptables.py
Labels: bug, enhancement

#1677 Add elf-header to MemoryDataSort. Closes angr/angr-management#107.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
Labels: bug

#1678 Support resolving TBB/TBH jump tables on ARM.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/test_jumptables.py
Labels: feature

#1672 Enhance structurer
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
Labels: enhancement

#1684 CFGEmulated: Allow resuming without having starts.
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#1686 CFGEmulated: Fix .resume(). Add a test case.
  angr/analyses/cfg/cfg_emulated.py
  tests/test_cfgemulated.py
Labels: bug

#1681 Help remove tmp variables in AIL statements
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/dataset.py
  angr/engines/light/engine.py
Labels: enhancement

#1673 Fix issues in ForwardAnalysis and StackPointerTracker.
  angr/analyses/forward_analysis.py
  angr/analyses/stack_pointer_tracker.py
Labels: bug

#1688 CFBlanket: Ignore sections that do not occupy memory.
  angr/analyses/cfg/cfb.py
Labels: bug
