Repository angr/angr, pull requests merged in 2020-04, with the labels that each got.

#2037 Unsat conditional exits should not make the parent unsat.
  angr/engines/successors.py
Labels: bug

#2034 angr database
  angr/analyses/cfg/cfb.py
  angr/analyses/reaching_definitions/dataset.py
  angr/angrdb/__init__.py
  angr/angrdb/db.py
  angr/angrdb/models.py
  angr/angrdb/serializers/__init__.py
  angr/angrdb/serializers/cfg_model.py
  angr/angrdb/serializers/comments.py
  angr/angrdb/serializers/funcs.py
  angr/angrdb/serializers/kb.py
  angr/angrdb/serializers/labels.py
  angr/angrdb/serializers/loader.py
  angr/angrdb/serializers/xrefs.py
  angr/errors.py
  angr/knowledge_base/knowledge_base.py
  angr/knowledge_plugins/cfg/cfg_manager.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_parser.py
  angr/knowledge_plugins/labels.py
  angr/knowledge_plugins/variables/variable_access.py
  angr/knowledge_plugins/xrefs/xref.py
  angr/knowledge_plugins/xrefs/xref_manager.py
  angr/project.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  setup.py
  tests/test_cfgfast.py
  tests/test_db.py
  tests/test_serialization.py
Labels: feature

#2038 Definition should not take into account its data.
  angr/analyses/reaching_definitions/dataset.py
  angr/analyses/reaching_definitions/definition.py
Labels: bug

#2044 CFGFast: Avoid unnecessarily enumerating object.sections.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#2045 CFGFast: Fix: Decoding ud2 marks the next two bytes as nodecode.
  angr/analyses/cfg/cfg_fast.py
  tests/test_vex.py
Labels: bug

#2046 CFGFast: Fix: ud2 on x86 goes undetected. Fixes #1963.
  angr/analyses/cfg/cfg_fast.py
  tests/test_vex.py
Labels: bug

#2049 The first preliminary implementation of C++ SimProcedure/functions support.
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/libstdcpp.py
  angr/procedures/libstdcpp/__init__.py
  angr/procedures/libstdcpp/std____throw_length_error.py
  angr/procedures/libstdcpp/std____throw_logic_error.py
  angr/procedures/libstdcpp/std__terminate.py
  angr/procedures/procedure_dict.py
Labels: feature

#2050 arg_locs: is_fp should also rely on is_fp_arg().
  angr/calling_conventions.py
Labels: bug

#2051 SimProcedure: Rename __altnames__ to ALT_NAMES.
  angr/procedures/libstdcpp/std____throw_length_error.py
  angr/procedures/libstdcpp/std____throw_logic_error.py
  angr/procedures/libstdcpp/std__terminate.py
  angr/procedures/procedure_dict.py
  angr/sim_procedure.py
Labels: refactor

#2052 Decompilation improvements 04/12/2020
  angr/analyses/decompiler/ailgraph_walker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/utils.py
  angr/analyses/reaching_definitions/engine_ail.py
  tests/test_baseptr_save_simplifier.py
  tests/test_structurer.py
Labels: bug, enhancement

#2055 Add eager-return simplifier.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/structured_codegen.py
Labels: feature

#2056 Add IfElseFlattener.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/region_simplifier.py
  angr/analyses/decompiler/sequence_walker.py
Labels: feature

#2057 Decompilation improvements 04/13/2020
  angr/analyses/decompiler/ailgraph_walker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/utils/__init__.py
  angr/utils/timing.py
  tests/test_baseptr_save_simplifier.py
Labels: enhancement, feature

#2059 RegionIdentifier: Recompute endnodes after removing cycles from the graph.
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/region_identifier.py
  tests/test_decompiler.py
Labels: bug

#2058 Deeper copy in `CFGManager`
  angr/knowledge_plugins/cfg/cfg_manager.py
  tests/test_cfg_manager.py
Labels: bug

#2061 angr.distributed
  angr/__init__.py
  angr/distributed/__init__.py
  angr/distributed/server.py
  angr/distributed/worker.py
  angr/exploration_techniques/__init__.py
  angr/exploration_techniques/bucketizer.py
Labels: feature

#2062 ReachingDefinitions: Be less conservative at call sites.
  angr/analyses/reaching_definitions/engine_ail.py
  angr/procedures/definitions/glibc.py
Labels: enhancement

#2063 VariableRecoveryFast: Do not write to stack if the offset is not a constant.
  angr/analyses/variable_recovery/variable_recovery_fast.py
  tests/test_decompiler.py
Labels: bug

#2065 Bug fix: Edge data got wrapped twice during AIL graph conversion.
  angr/analyses/decompiler/ailgraph_walker.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: bug

#2068 FunctionSerializer: Fix a bug with external functions/blocks.
  angr/angrdb/serializers/funcs.py
  angr/knowledge_plugins/functions/function_parser.py
Labels: bug

#2069 VariableAccess: Make it hashable.
  angr/knowledge_plugins/variables/variable_access.py
Labels: bug

#2067 CFGFast: Handle exceptions.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
  angr/knowledge_plugins/functions/function_parser.py
  angr/protos/cfg_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  angr/protos/xrefs_pb2.py
  angr/utils/enums_conv.py
Labels: feature

#2071 CFBlanket: Support adding memory data.
  angr/analyses/cfg/cfb.py
Labels: feature

#2072 CFGNode: Restore instruction_addrs after unserialization.
  angr/knowledge_plugins/cfg/cfg_node.py
Labels: enhancement

#1961 InitializationFinder analysis
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/init_finder.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/analyses/xrefs.py
  angr/engines/light/engine.py
  tests/test_calling_convention_analysis.py
  tests/test_init_finder.py
  tests/test_xrefs.py
Labels: feature

#2083 VariableRecoveryFast: Handle aligning stack pointers by masking.
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: bug

#2053 Handle tailcalls when making return edges with detect_tail_calls set
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: bug

#2085 Type inference and many other fixes
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_utils.py
  angr/analyses/code_tagging.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/utils.py
  angr/analyses/dominance_frontier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/values.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/uses.py
  angr/analyses/typehoon/__init__.py
  angr/analyses/typehoon/lifter.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/engines/light/engine.py
  angr/keyed_region.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/procedures/libstdcpp/_unwind_resume.py
  angr/procedures/libstdcpp/std____throw_bad_alloc.py
  angr/procedures/libstdcpp/std____throw_bad_cast.py
  angr/sim_type.py
  angr/sim_variable.py
  angr/utils/__init__.py
  tests/test_decompiler.py
  tests/test_structurer.py
  tests/test_typehoon.py
Labels: feature

#2090 CFGFast: Fix the incorrect ins_addr and stmt_idx on branch edges.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#2092 Enable indirect jump marking on ARM architectures.
  angr/analyses/disassembly_utils.py
Labels: feature

#2091 Add a fast ARM ELF indirect jump resolver.
  angr/analyses/cfg/indirect_jump_resolvers/__init__.py
  angr/analyses/cfg/indirect_jump_resolvers/arm_elf_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
Labels: feature

#2096 Function.graph_ex(): Fix a bug that may lead to infinite loops.
  angr/knowledge_plugins/functions/function.py
Labels: bug

#2097 VariableRecoveryFast: Implement comparison operations.
  angr/analyses/variable_recovery/engine_vex.py
Labels: bug
