Repository angr/angr, pull requests merged in 2020-06, with the labels that each got.

#2184 RDA: Do not re-initialize ReachingDefinitionState when copying.
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/reachingdefinitions_results/x86_64/all_definitions.pickle
  tests/reachingdefinitions_results/x86_64/fauxware_definitions.pickle
  tests/reachingdefinitions_results/x86_64/loop_definitions.pickle
Labels: bug

#2190 Do not pickle the analyses hub with Project.
  angr/misc/plugins.py
  angr/project.py
  tests/test_pickle.py
Labels: bug

#2191 VEXHeavy: Do not add the same guard twice.
  angr/engines/vex/heavy/heavy.py
Labels: bug

#2042 CFG visitor on a slice
  angr/analyses/cfg_slice_to_sink/__init__.py
  angr/analyses/cfg_slice_to_sink/cfg_slice_to_sink.py
  angr/analyses/cfg_slice_to_sink/graph.py
  angr/analyses/cfg_slice_to_sink/transitions.py
  angr/analyses/forward_analysis/__init__.py
  angr/analyses/forward_analysis/visitors/__init__.py
  angr/analyses/forward_analysis/visitors/cfg.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/reaching_definitions/subject.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/cfg_node.py
  tests/analyses/__init__.py
  tests/analyses/cfg_slice_to_sink/__init__.py
  tests/analyses/cfg_slice_to_sink/test_cfg_slice_to_sink.py
  tests/analyses/cfg_slice_to_sink/test_graph.py
  tests/analyses/cfg_slice_to_sink/test_transitions.py
  tests/analyses/forward_analysis/__init__.py
  tests/analyses/forward_analysis/visitors/__init__.py
  tests/analyses/forward_analysis/visitors/test_cfg.py
  tests/analyses/reaching_definitions/__init__.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/all_visited_blocks.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_visited_blocks.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_visited_blocks.pickle
  tests/analyses/reaching_definitions/test_dep_graph.py
  tests/analyses/reaching_definitions/test_rd_state.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
  tests/analyses/reaching_definitions/test_subject.py
  tests/test_dep_graph.py
  tests/test_reachingdefinitions.py
Labels: feature

#2197 Inter-procedural computation of the dependency graph
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/function_handler.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/code_location.py
  angr/engines/light/engine.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: enhancement

#2199 Make SimEngineLight._context always return a tuple.
  angr/engines/light/engine.py
Labels: bug

#2200 DepGraph.transitive_closure: Always include the beginning def node.
  angr/analyses/reaching_definitions/dep_graph.py
  tests/analyses/reaching_definitions/test_dep_graph.py
Labels: bug

#2203 RDA VEX engine: Fix the check of external functions.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug

#2204 CFGFast: Do not allow overlapping ARM blocks with different modes.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#2066 Indirect Resolver for Constant Values
  angr/analyses/cfg/indirect_jump_resolvers/__init__.py
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/propagator.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/propagations.py
Labels: feature

#2207 IfSimplifier: Gracefully handle non-constant conditional branch targets.
  angr/analyses/decompiler/region_simplifier.py
Labels: bug

#2186 tags support for definitions in RD
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/definition.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
Labels: feature

#2208 CFGFast: Fix out-of-bound data load caused by aligning. Fix #2201.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#2210 CFGFast: Detect more cases of GP setting on MIPS binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
Labels: bug, enhancement

#2213 Decompiler: Add ConstantDereferencesSimplifier.
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/ailgraph_walker.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/const_derefs.py
Labels: feature

#2212 Refactored resolved_addrs kb to store resolves
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/knowledge_plugins/indirect_jumps.py
  tests/test_kb_plugins.py
Labels: refactor

#2215 Parse GNU C++ mangled function names and extract types.
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/libstdcpp.py
  angr/procedures/libstdcpp/std____throw_length_error.py
  angr/procedures/libstdcpp/std____throw_logic_error.py
  angr/procedures/stubs/ReturnUnconstrained.py
  angr/sim_type.py
  angr/utils/library.py
  setup.py
  tests/test_types.py
Labels: feature

#2205 Fixed Windows state_blank thread handling
  angr/simos/windows.py
Labels: bug

#2216 Get rid of SimCppNamespaced. Allow naming certain types.
  angr/sim_type.py
  tests/test_types.py
Labels: enhancement

#2217 Typehoon: Infer types of loads from non-constant offsets.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  tests/test_decompiler.py
Labels: feature

#2219 Typehoon: Infer types of stores to non-constant offsets.
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  tests/test_decompiler.py
Labels: bug, enhancement

#2227 distributed: Fix status control.
  angr/distributed/server.py
  angr/distributed/worker.py
  angr/exploration_techniques/spiller.py
  angr/vaults.py
Labels: bug

#2228 Multiple improvements on RDA and other things
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/reaching_definitions/call_trace.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/function_handler.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/reaching_definitions/subject.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/engines/light/engine.py
  angr/knowledge_plugins/key_definitions/definition.py
  angr/sim_type.py
  angr/utils/__init__.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: bug, enhancement, feature

#2229 Display demangled C++ function names in disasm and decompiler.
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/disassembly.py
  angr/project.py
  angr/utils/library.py
Labels: enhancement
