Repository angr/angr, pull requests merged in 2020-07, with the labels that each got.

#2235 MIPSElfFastResolver: Handle more cases of gp resolving.
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
  angr/exploration_techniques/slicecutor.py
  tests/test_cfgfast.py
Labels: enhancement

#2239 Fixed indirect_jump_resolvers reusing func_addr for ijk_calls to outs…
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#2202 RDA no longer supports CFGSliceToSink.
  angr/analyses/forward_analysis/__init__.py
  angr/analyses/forward_analysis/visitors/__init__.py
  angr/analyses/forward_analysis/visitors/cfg.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/reaching_definitions/subject.py
  tests/analyses/forward_analysis/__init__.py
  tests/analyses/forward_analysis/visitors/__init__.py
  tests/analyses/forward_analysis/visitors/test_cfg.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
  tests/analyses/reaching_definitions/test_subject.py
Labels: enhancement

#2256 Pin cffi to >=1.14.0, fixes #2255
  setup.py
Labels: bug

#2257 Make CodeLocation.__repr__() less verbose.
  angr/code_location.py
Labels: refactor

#2258 CFGFast: Fix an issue of missing src insaddrs.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#2260 Fixed address for new ITE ConditionNodes
  angr/analyses/decompiler/structurer.py
Labels: bug

#2262 VR-AIL: Recognize stack variables that are only referenced once.
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  tests/test_decompiler.py
Labels: enhancement

#2268 Reassembler: Only remove unnecessary functions when glibc is present.
  angr/analyses/reassembler.py
Labels: feature

#2270 Keep AIL expr tags in propagator and decompilation.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/propagator/engine_ail.py
Labels: enhancement

#2269 Patches: Support applying patches to a binary. Add a test case.
  angr/knowledge_plugins/patches.py
  tests/test_patches.py
Labels: enhancement

#2280 StructuredCodegen: Store tags in CExpr classes.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2281 Move all AIL analyses to angr.
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  tests/test_block_simplifier.py
  tests/test_callsite_maker.py
Labels: refactor

#2282 Decompiler: Support folding calls into other expressions.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/code_location.py
  angr/engines/light/engine.py
  angr/knowledge_plugins/key_definitions/uses.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
  tests/test_decompiler.py
Labels: feature
