Repository angr/angr, pull requests merged in 2020-01, with the labels that each got.

#1897 CFGFast: Detect no-op instruction mov reg0, reg0.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#1899 JumptableResolver: Check if stmt_idx == DEFAULT_STATEMENT before accessing block.statements.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#1896 CFGFast: Fix the bug that disabled cc detection. Add a test.
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: bug

#1901 CFBlanket: Support PE files.
  angr/analyses/cfg/cfb.py
Labels: enhancement

#1906 Enable strict_block_end with explicit max size in CFG. Close #1905
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  tests/test_lifter.py
Labels: bug

#1908 Suppress some warnings about symbolic memory reads during CFG recovery.
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
  angr/procedures/glibc/__libc_start_main.py
Labels: enhancement

#1918 JumptableResolver: Add expected ccalls for AARCH64. Close #1917.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#1926 Do not complain about exit states with over 0 solutions.
  angr/engines/successors.py
Labels: enhancement

#1931 claripy: ccall: add adcx/adox support
  angr/engines/vex/claripy/ccall.py
  tests/test_vex.py
Labels: enhancement

#1938 CFG: Support getting function addresses through FDEs for ELFs.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#1942 Ensure that decompilation only works on normalized function graphs.
  angr/analyses/decompiler/clinic.py
  tests/test_baseptr_save_simplifier.py
  tests/test_clinic.py
  tests/test_decompiler.py
Labels: enhancement

#1941 Structurer: _bool_variable_from_ail_condition() should return a Bool when proper.
  angr/analyses/decompiler/structurer.py
Labels: bug

#1944 Structurer: Internal calls to Structurer should inherit the current condition mapping.
  angr/analyses/decompiler/structurer.py
Labels: bug

#1943 ConditionalBreakNode.condition must be claripy ASTs (before the final pass)
  angr/analyses/decompiler/structurer.py
Labels: bug

#1950 Add a db-backend for Spiller.
  angr/exploration_techniques/spiller.py
  tests/test_spiller.py
Labels: feature
