Repository angr/angr, pull requests merged in 2020-12, with the labels that each got.

#2408 Refactor CodeLocation and type its properties.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/code_location.py
  angr/engines/light/engine.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: bug, refactor

#2415 Enable optimization passes for non-standard platforms.
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/misc/loggers.py
  angr/state_plugins/inspect.py
  tests/test_decompiler.py
Labels: feature

#2416 Add an optimization to remove excessive conditionals.
  angr/analyses/decompiler/condition_processor.py
  tests/test_decompiler.py
Labels: feature

#2419 ConditionProcessor: Support claripy operation Extract.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#2421 CongruencyChecker: Implement a weaker constraints equivalence check.
  angr/analyses/congruency_check.py
Labels: enhancement

#2423 Speed up code generation by memoization and depth cutoff.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2424 Clinic: Remove alignment blocks from function graphs.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: enhancement

#2425 Fix some decompiler issues
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2417 SimProcedure: add `poll`
  angr/procedures/posix/poll.py
Labels: feature

#2429 Support handling and codegen of signed operations.
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: enhancement

#2440 Decompiler: Handle calculated direct jumps.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  tests/test_decompiler.py
Labels: enhancement

#2442 Add a test case for addition-based data refs collection.
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: enhancement

#2443 Decompiler: Support return statements.
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/engines/light/engine.py
Labels: feature

#2445 Clinic: Do not crash if function has no CC. Close #2444.
  angr/analyses/decompiler/clinic.py
Labels: bug
