Repository angr/angr, pull requests merged in 2020-03, with the labels that each got.

#1975 Set typedef types as having a label with their given name
  angr/sim_type.py
Labels: feature

#1977 SimBottom now takes a label. SimTypeChar() can be unsigned.
  angr/sim_type.py
Labels: feature

#1978 Utils.library: Add cprotos2py().
  angr/analyses/calling_convention.py
  angr/utils/library.py
Labels: feature

#1980 DominanceFrontier: Speed up graph creation by fixing __hash__().
  angr/utils/graph.py
Labels: bug

#1976 Update glibc prototypes to include func args and pre-typedef names.
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/glibc.py
  angr/sim_type.py
  tests/test_types.py
Labels: enhancement, refactor

#1972 Fix multiple issues with propagator and its AIL engine.
  angr/analyses/calling_convention.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/keyed_region.py
  angr/knowledge_plugins/functions/function.py
  tests/test_decompiler.py
Labels: bug, enhancement

#1987 Make angr errors with multiple arguments picklable.
  angr/errors.py
Labels: bug

#1989 Structurer: Support structuring loops with abnormal exits.
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: feature

#1990 Structurer: Overwrite the array element before eliminating other elements.
  angr/analyses/decompiler/structurer.py
Labels: bug

#1991 Optimize the speed of decompilation
  angr/analyses/decompiler/clinic.py
  angr/analyses/reaching_definitions/dataset.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/live_definitions.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  tests/reachingdefinitions_results/x86_64/all_definitions.pickle
  tests/reachingdefinitions_results/x86_64/fauxware_definitions.pickle
  tests/reachingdefinitions_results/x86_64/loop_definitions.pickle
Labels: enhancement

#1994 Decomplation improvements 03/11/2020
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: bug, enhancement, feature

#1996 Structurer: Support switch-case structures.
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/engine_ail.py
  angr/errors.py
  tests/test_decompiler.py
Labels: bug, feature

#2000 conditionally zero allocated memory
  angr/procedures/win32/heap.py
  angr/state_plugins/heap/heap_freelist.py
  angr/state_plugins/heap/heap_ptmalloc.py
Labels: enhancement

#2008 Fix the postdom optimization for acyclic regions.
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
Labels: bug

#2009 Add prototypes for variadic glibc functions.
  angr/calling_conventions.py
  angr/procedures/definitions/glibc.py
  angr/sim_type.py
  angr/utils/library.py
Labels: enhancement

#2011 Structurer: Do not generate redundant while(true) around LoopNodes.
  angr/analyses/decompiler/structurer.py
Labels: enhancement

#2010 Optimize the O(n!) implementation of RegionIdentifier.slice_graph().
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/reaching_definitions/def_use_graph.py
  angr/utils/graph.py
  tests/test_decompiler.py
  tests/test_def_use_graph.py
Labels: bug

#2012 CFGBase: Stricter PLT stub removal to avoid wrong removals.
  angr/analyses/cfg/cfg_base.py
  tests/test_cfgfast.py
Labels: bug

#2015 GraphRegion: Do not generate [None] as self.successors.
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#1676 Function Definitions application and some related changes
  angr/knowledge_plugins/functions/function.py
  tests/test_function.py
  tests/test_types.py
Labels: enhancement

#2016 StructuredCodegen: Support outputting arguments without function prototypes.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2018 Decompilation improvements 03/25/2020
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/utils/graph.py
Labels: bug, enhancement

#2019 Structurer: Support merging sequence nodes when removing empty ones.
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
  tests/test_decompiler.py
Labels: enhancement

#2021 Decompilation improvements 03/26/2020
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/engines/light/engine.py
Labels: bug, enhancement

#2023 Add support of Cmp{GT,GE,LT,LE,NE} in some AIL-based static analyses.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: enhancement

#2025 SimCC.arg_logs(): Check the existence of both func_ty and args.
  angr/calling_conventions.py
Labels: enhancement

#2024 Decompilation improvements 03/27/2020
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifier.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
  angr/analyses/decompiler/utils.py
Labels: bug, enhancement, feature

#2026 Add Or and Div support to ConditionProcessor and Codegen.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2029 Decompilation improvements 03/28/2020.
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/dep_graph.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/live_definitions.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  tests/test_dep_graph.py
  tests/test_reachingdefinitions.py
Labels: bug, enhancement
