Repository angr/angr, pull requests merged in 2020-10, with the labels that each got.

#2345 Unicorn engine now returns the PC after syscall for MIPS.
  angr/state_plugins/unicorn_engine.py
Labels: bug

#2346 Address several issues with unicorn-based MIPS execution.
  angr/calling_conventions.py
  angr/procedures/posix/dup.py
  angr/state_plugins/unicorn_engine.py
Labels: bug

#2347 JumptableResolver: Handle more jumptables in AMD64 binaries.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/test_jumptables.py
Labels: feature

#2349 ConditionProcessor: Use BVS.name to key the condition mapping.
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#2350 StucturedCodegen: Store tags for CConstants.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2351 Typehoon: Add 32-bit types support.
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/translator.py
Labels: feature

#2359 Fix the problem of mising arch in `func_ty`s.
  angr/calling_conventions.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
Labels: bug

#2362 JumptableResolver: Avoid redundant memory writes for symbolic addrs.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/concretization_strategies/__init__.py
  angr/concretization_strategies/unlimited_range.py
  angr/procedures/glibc/__libc_start_main.py
  angr/storage/memory_mixins/__init__.py
  angr/storage/memory_mixins/bvv_conversion_mixin.py
  angr/storage/memory_mixins/regioned_memory/__init__.py
  angr/storage/memory_mixins/regioned_memory/regioned_address_concretization_mixin.py
  angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py
Labels: bug, enhancement

#2364 Interleave concretized addresses to speed up solving.
  angr/storage/memory_mixins/address_concretization_mixin.py
Labels: enhancement

#2328 Add new engine based on Ghidra's P-Code IR
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/engines/__init__.py
  angr/engines/pcode/__init__.py
  angr/engines/pcode/behavior.py
  angr/engines/pcode/emulate.py
  angr/engines/pcode/engine.py
  angr/engines/pcode/lifter.py
  setup.py
Labels: feature

#2365 Fix test_fauxware_oppologist.
  tests/test_oppologist.py
Labels: bug
