Repository angr/angr, pull requests merged in 2021-05, with the labels that each got.

#2623 Decompiler: Add a few more optimizations.
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/extended_byte_and_mask.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_bitmasks.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_ite_branch.py
Labels: feature

#2642 CFGFast: Properly handle artificial cold functions when in switch-cases.
  angr/analyses/cfg/cfg_base.py
  tests/test_decompiler.py
Labels: enhancement

#2645 Recover variables in ITEs. Do not rebuild Assignment.dst.
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  tests/test_decompiler.py
Labels: bug

#2646 Multiple fixes in decompiler.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/propagator/engine_ail.py
Labels: bug

#2649 Less aggressively unify register variables.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: enhancement

#2648 Do not aggressively make condition nodes in unstructured sequence nodes.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structurer.py
Labels: bug

#2650 Adapt JumpTableProcessor to the new light engine implementation.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/engines/light/engine.py
Labels: enhancement

#2651 CFGFast: Do not duplicate indirect jump resolvers.
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
Labels: bug

#2654 Structurer: Fix a bug where subexprs in Or exprs are missing.
  angr/analyses/decompiler/utils.py
Labels: bug

#2653 Decompiler: Use phi-relationships to unify register variables.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: enhancement

#2658 Structurer: Remove redundant jumps.
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: enhancement

#2661 Structurer: Use guarding conditions in certain scenarios.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#2662 Address CFGFast crashes of args' lengths must all be equal.
  angr/engines/light/engine.py
  tests/test_cfgfast.py
Labels: bug

#2669 Propagator: Fix the loss of propagation result.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/propagator/propagator.py
  angr/state_plugins/sim_action.py
  tests/test_decompiler.py
Labels: bug

#2668 Multiple fixes to fix issue #2643.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/cooperation.py
  tests/test_decompiler.py
Labels: bug

#2673 Add some missing handlers to Propagator, RDA, and VR.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
Labels: enhancement

#2675 VRA: Traverse each block more than once to make sure we do not lose accesses to phi nodes.
  angr/analyses/decompiler/clinic.py
  angr/analyses/typehoon/translator.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: bug

#2674 Clinic: Set arch to function prototype.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2678 Support collecting data references from LoadG.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#2679 Add gets.
  angr/procedures/libc/gets.py
  angr/state_plugins/libc.py
Labels: feature

#2689 CFGFast: Add support for ARM UND instructions.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#2695 CFGBase: Add ud{0,1,2} to noop insn detection.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#2696 CCCA: Improve its robustness.
  angr/analyses/complete_calling_conventions.py
  angr/engines/vex/light/light.py
Labels: bug

#2693 Enforce correct endianness when using ConcreteTarget
  angr/storage/memory_mixins/default_filler_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/ultra_page.py
Labels: bug

#2694 JumptableRecovery: Handle C-style VTables.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/knowledge_plugins/cfg/indirect_jump.py
  tests/test_jumptables.py
Labels: feature

#2697 Function: Only add each node once.
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#2700 VRA: Avoid redundant MO set comparisons.
  angr/analyses/variable_recovery/variable_recovery_base.py
Labels: enhancement

#2699 GraphVisitor: Ditch SortedSet for a faster queue.
  angr/analyses/forward_analysis/forward_analysis.py
  angr/analyses/forward_analysis/visitors/graph.py
  angr/utils/algo.py
Labels: enhancement

#2703 ForwardAnalysis: Merge all input states in one batch before they are needed.
  angr/analyses/forward_analysis/forward_analysis.py
  angr/analyses/loop_analysis.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/stack_pointer_tracker.py
  angr/analyses/variable_recovery/variable_recovery.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/analyses/vfg.py
  angr/knowledge_plugins/key_definitions/environment.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/knowledge_plugins/key_definitions/uses.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
Labels: enhancement

#2704 (MV)ListPage: Optimize for no-sinkhole cases.
  angr/analyses/reaching_definitions/__init__.py
  angr/storage/memory_mixins/paged_memory/pages/list_page.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: enhancement

#2706 Structurer: Guarding conditions should not impact structuring.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structurer.py
Labels: bug
