Repository angr/angr, pull requests merged in 2021-12, with the labels that each got.

#2993 Create SimMissingTempError.
  angr/engines/vex/heavy/super_fastpath.py
  angr/errors.py
  angr/state_plugins/scratch.py
Labels: bug

#2969 CFGFast: Smarter complete scan. Improves performance on ARM binaries.
  angr/analyses/cfg/cfg_arch_options.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/segment_list.py
  angr/analyses/forward_analysis/forward_analysis.py
  angr/block.py
  tests/test_cfg_thumb_firmware.py
  tests/test_cfgfast.py
  tests/test_jumptables.py
Labels: bug, enhancement

#2998 tracer exploration: Fix qemu block contained in unicorn block check
  angr/exploration_techniques/tracer.py
Labels: bug

#2999 RDA: VEX engine: Add a handler for Mull.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/engines/light/engine.py
Labels: feature

#3000 CFG: Only merge nodes when the first one does not end with a branch.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#3001 CCA: Use function prototypes' calling convention for PLTs if available.
  angr/analyses/calling_convention.py
Labels: bug

#3006 SimCCSystemVAMD64: Fix a bug when flattening arrays and structs.
  angr/calling_conventions.py
  tests/broken_simcc.py
  tests/test_calling_conventions.py
Labels: bug

#3007 Fix the missing arch argument when calling refine_locs_with_struct_type().
  angr/calling_conventions.py
Labels: bug

#3008 Fix a bug in how refine_locs_with_struct_type layouts array arguments.
  angr/calling_conventions.py
  tests/test_calling_conventions.py
Labels: bug

#3009 RDA.VexEngine: Handles SimStructArg and SimArrayArg.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: enhancement

#3010 Decompiler: Aggressively display string references.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: feature

#3011 Disassembly: Fix redundant spaces between operands and missing prefixes.
  angr/analyses/disassembly.py
Labels: bug

#3004 CFGFast: Better handle constant pools in ARM binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  angr/engines/vex/lifter.py
  angr/factory.py
Labels: enhancement

#3013 Structurer: Stronger condition simplifiers for better readability. Close #2975.
  angr/analyses/decompiler/condition_processor.py
  setup.py
Labels: enhancement

#3016 CompleteCCA: Reanalyze a function if it doesn't have a CC or a prototype.
  angr/analyses/complete_calling_conventions.py
Labels: bug

#3018 StructuredCodeGen: Prioritize string references when rendering constants.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: enhancement

#3017 VariableRecovery: Create global variables based on references.
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_base.py
Labels: enhancement

#3019 StructuredCodeGen: Only generate a newline if there are local variables.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3024 CFGModel: Implement a faster get_any_node() when anyaddr is True.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: refactor

#3032 Decompiler: Support handling and simplifying VEX ccalls.
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/ccall_rewriters/__init__.py
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/decompiler/ccall_rewriters/rewriter_base.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/region_simplifier.py
  angr/analyses/decompiler/region_simplifiers/__init__.py
  angr/analyses/decompiler/region_simplifiers/cascading_cond_transformer.py
  angr/analyses/decompiler/region_simplifiers/cascading_ifs.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/goto.py
  angr/analyses/decompiler/region_simplifiers/if_.py
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/region_simplifiers/loop.py
  angr/analyses/decompiler/region_simplifiers/node_address_finder.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/engine_ail.py
  tests/test_decompiler.py
Labels: feature

#3033 CFGFast: Only apply function edges in CFGJobs if _generate_cfgnode succeeds.
  angr/analyses/cfg/cfg_fast.py
Labels: refactor

#3037 Speed up loading by delaying loading of win32api definitions.
  angr/misc/autoimport.py
  angr/procedures/definitions/__init__.py
  angr/simos/windows.py
Labels: enhancement

#3043 VRA: Use replace_annotations() to reduce the number of created ASTs.
  angr/analyses/variable_recovery/variable_recovery_base.py
Labels: enhancement

#3041 VRA: Do not create variables for artificial registers.
  angr/analyses/variable_recovery/engine_base.py
Labels: bug

#3042 PagedMemoryMixin: Optimization: Do not compare bytes for the same page.
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
Labels: enhancement

#3044 Fix the timeout issue in test_floating_point_memory_reads.
  tests/test_tracer.py
Labels: bug
