Repository angr/angr, pull requests merged in 2021-01, with the labels that each got.

#2450 CCA: Fix CC matching failures when functions store regs.
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/variables/variable_access.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_calling_convention_analysis.py
Labels: enhancement

#2451 AIL: Add support for concat.
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/engines/light/engine.py
Labels: enhancement

#2452 Disable cross-insn-opt in IRSBs for indirect jump resolving. Close #2448.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#2453 Fix a bug in readv(). Close #2447.
  angr/procedures/linux_kernel/iovec.py
Labels: bug

#2467 Dereference read-only pointers in CFG and decompiler.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/block_simplifier.py
  tests/test_peephole_optimizations.py
Labels: enhancement

#2483 Typehoon: Pad structs.
  angr/analyses/typehoon/translator.py
Labels: bug

#2482 Fixing source-to-disassembly correspondance for decompilation
  angr/analyses/decompiler/structured_codegen.py
Labels: feature

#2484 Propagator: Correctly detect overwritten variables in AIL engine.
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
Labels: bug

#2485 Suppor coalescing cascading Ifs.
  angr/analyses/decompiler/region_simplifier.py
Labels: feature

#2487 Decompiler: Isolate peephole optimizations.
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_sub_n.py
  angr/analyses/decompiler/peephole_optimizations/base.py
  angr/analyses/decompiler/peephole_optimizations/bool_expr_xor_1.py
  angr/analyses/decompiler/peephole_optimizations/coalesce_same_cascading_ifs.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/peephole_optimizations/conv_shl_shr.py
  angr/analyses/decompiler/peephole_optimizations/one_sub_bool.py
  angr/analyses/decompiler/peephole_optimizations/remove_empty_if_body.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_bitmasks.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_nots.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_shifts.py
  angr/analyses/decompiler/peephole_optimizations/single_bit_xor.py
  tests/test_peephole_optimizations.py
Labels: enhancement, feature

#2486 AILSimplifier: Support expression folding.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
Labels: feature

#2489 StructuredCodeGen: Pretty print temporary variables.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2488 Enable some optimization passes for ARMCortexM.
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
Labels: enhancement

#2492 StructuredCodeGen: memo should also memoize is_expr.
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2494 RDA: Do not crash if reg_offset is not in arch.registers dict.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug

#2493 Propagator: Do not propagate tmps across blocks in AIL mode.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/engine_base.py
  angr/analyses/propagator/propagator.py
Labels: bug

#2496 Fixing disass-to-source correlation for tabing
  angr/analyses/decompiler/structured_codegen.py
Labels: feature, work in progress

#2498 StructuredCodeGen: Output variable for Call.ret_expr when available.
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2499 Fixing locating first-use variables from disassembly
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2501 CondProc: Fix incorrect claripy AST to AIL AST conversion for Not.
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#2502 Add a peephole optimization for <s 0.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/conv_a_sub0_shr_and.py
Labels: feature

#2504 VariableRecovery: Creating global variables that are only loaded.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_decompiler.py
Labels: feature

#2505 Fix function locating from the posmap
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2506 Fixed highlighting for functions, constants, and constant tabbing
  angr/analyses/decompiler/structured_codegen.py
Labels: bug

#2507 Added tracking to closure objects in decompiler posmap
  angr/analyses/decompiler/structured_codegen.py
Labels: feature

#2508 Fix multiple issues in AILSimplifier.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/conv_a_sub0_shr_and.py
  angr/knowledge_plugins/key_definitions/uses.py
Labels: bug

#2503 Add __getdelim implementation
  angr/procedures/libc/getdelim.py
Labels: enhancement
