Repository angr/angr, pull requests merged in 2021-09, with the labels that each got.

#2885 indirect call resolution correctly propagates gp value from stack
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
Labels: bug

#2891 Clinic: Assign an idx to Call.ret_expr expressions.
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  tests/test_decompiler.py
Labels: bug

#2892 Structurer: Addresses multiple causes for non-determinism.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: bug

#2893 Propagator: Tighten the call expression replacement check.
  angr/analyses/propagator/call_expr_finder.py
  angr/analyses/propagator/propagator.py
  tests/test_decompiler.py
Labels: bug

#2894 CCA: Enable callsite analysis for missing library functions.
  angr/analyses/calling_convention.py
  angr/knowledge_plugins/functions/function.py
  tests/test_calling_convention_analysis.py
  tests/test_decompiler.py
Labels: feature

#2895 StackCanarySimplifier: Support more cases.
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  tests/test_decompiler.py
Labels: enhancement, refactor

#2896 CCA: Analyze callsite once for missing library functions.
  angr/analyses/calling_convention.py
Labels: enhancement

#2897 LoopSimplifier: for loop iterators cannot be control-transferring statements.
  angr/analyses/decompiler/region_simplifier.py
  tests/test_decompiler.py
Labels: bug

#2898 VRA: Enable type inference for bp registers.
  angr/analyses/variable_recovery/engine_base.py
Labels: enhancement

#2860 Variable retyping support in decompiler
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/region_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/angrdb/serializers/structured_code.py
  angr/knowledge_plugins/structured_code/manager.py
  angr/knowledge_plugins/types.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/sim_type.py
  angr/sim_variable.py
  tests/test_decompiler.py
Labels: feature

#2901 CCA: Fix register argument detection in callsite analysis.
  angr/analyses/calling_convention.py
Labels: bug

#2902 CallsiteMaker: Support removing stored return addresses for indirect calls.
  angr/analyses/decompiler/callsite_maker.py
Labels: enhancement

#2903 Propagator: Fix a None accessing issue in the AIL engine.
  angr/analyses/propagator/engine_ail.py
Labels: bug

#2904 CStructuredCodeGen: Do not unify types for variables around a binary operator.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/typehoon.py
Labels: bug

#2905 Add function prototypes for __printf_chk and __fprintf_chk.
  angr/procedures/definitions/glibc.py
Labels: enhancement

#2906 CCodeGen: More accurate type casting and displaying.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typehoon.py
  tests/test_decompiler.py
Labels: feature

#2907 StructuredCodeManager: Support removing cached items.
  angr/knowledge_plugins/structured_code/manager.py
Labels: feature

#2909 Loggers: Enable/disable profiling messages separately.
  angr/misc/loggers.py
Labels: feature

#2912 Fix bug in decompilation when a string contains a single quote, the g…
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: bug

#2916 Structurer: Handle loop body blocks with jump statements not at the end of blocks.
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#2919 MVListPage: Unpack single-valued sets outside the tight loop.
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: enhancement

#2920 SimMemoryMixin: Introduce erase().
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/storage/memory_mixins/__init__.py
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/list_page.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: feature

#2922 unicorn_engine.py: Do not import pkg_resources by default.
  angr/state_plugins/unicorn_engine.py
Labels: enhancement
