Repository angr/angr, pull requests merged in 2021-07, with the labels that each got.

#2795 LightEngine: Catch SimOperationError in Unop handler.
  angr/engines/light/engine.py
Labels: bug

#2796 VRA: Fix an uncaught SimMemoryMissingError.
  angr/analyses/variable_recovery/engine_base.py
Labels: bug

#2797 Structurer: Transform nested if-else into cascading if-elseif.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/region_simplifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: feature

#2801 CFGBase: Do not crash if a return target does not exist in the binary.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#2692 FLIRT support
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/flirt.py
  angr/analyses/reassembler.py
  angr/flirt/__init__.py
  angr/flirt/build_sig.py
  angr/knowledge_plugins/cfg/cfg_manager.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_parser.py
  angr/protos/__init__.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  setup.py
  tests/test_flirt.py
Labels: feature

#2805 ListPage: Fix an issue of over-storing.
  angr/storage/memory_mixins/paged_memory/pages/list_page.py
Labels: bug

#2815 Serializing variable names and codegens into angr DB
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/__init__.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structured_codegen/dummy.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/angrdb/db.py
  angr/angrdb/models.py
  angr/angrdb/serializers/funcs.py
  angr/angrdb/serializers/kb.py
  angr/angrdb/serializers/structured_code.py
  angr/angrdb/serializers/variables.py
  angr/knowledge_plugins/functions/function_parser.py
  angr/knowledge_plugins/structured_code/manager.py
  angr/knowledge_plugins/variables/variable_access.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/protos/__init__.py
  angr/protos/variables.proto
  angr/protos/variables_pb2.py
  angr/sim_variable.py
Labels: feature

#2818 fix pretty print to avoid priting something like char *a[3]
  angr/sim_type.py
Labels: bug

#2821 CFGBase: Fix: Self-loops on the first node are incorrected marked as outside jumps.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#2820 CFGBase: Recognize single-node-with-self-loop alignment chunks.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#2822 CFGBase: Fix a crash in _process_irrational_function_starts() when blocks are empty.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#2824 VRA: Fix the wrong temp variable in VEXEngine._handle_LLSC.
  angr/analyses/variable_recovery/engine_vex.py
Labels: bug

#2823 RegionIdentifier: Do not crash if the beginning node has a self loop.
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#2825 CStructuredCodeGen: Fix two missing yielded items.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#2826 Propagator: AIL engine's memory model is now aware of partially zeroed register and memory bytes.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/prop_value.py
  angr/analyses/propagator/propagator.py
  angr/storage/memory_mixins/paged_memory/pages/cooperation.py
  tests/test_block_simplifier.py
  tests/test_decompiler.py
Labels: enhancement

#2828 Use blocks obtained from self.blocks directly in instruction_size
  angr/knowledge_plugins/functions/function.py
  tests/test_function.py
Labels: bug

#2835 RDA: Multiple robustness improvements.
  angr/analyses/reaching_definitions/dep_graph.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/knowledge_plugins/key_definitions/atoms.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: bug, enhancement

#2836 MemoryObjectSetMixin: Properly handle cross-page writes.
  angr/storage/memory_mixins/paged_memory/pages/cooperation.py
Labels: bug

#2837 Rebuild callgraph after loading angr DB.
  angr/angrdb/serializers/funcs.py
  angr/knowledge_plugins/functions/function_manager.py
Labels: bug

#2839 ConditionProcessor: Use AST._hash as keys for memo to avoid testing equivalence between ASTs.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#2840 ConstantDereferenceSimplifier: Segment.is_writable is a property.
  angr/analyses/decompiler/optimization_passes/const_derefs.py
Labels: bug

#2841 VRA: Fix two cases where operands are incorrectly sized.
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
Labels: bug
