Repository angr/angr, pull requests merged in 2021-03, with the labels that each got.

#2544 SimUserland: Fill in syscall_abis before calling configure_project().
  angr/simos/userland.py
Labels: bug

#2545 added better highlighting for func names and simpler unified var access
  angr/analyses/decompiler/structured_codegen.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: refactor

#2547 removed public access to unified variables
  angr/analyses/decompiler/structured_codegen.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: refactor

#2551 Use unsigned ints for addresses and sizes.
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/protos/__init__.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
Labels: bug

#2556 Make SimInspector.action() faster.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/sim_state.py
  angr/state_plugins/inspect.py
  tests/perf_concrete_execution.py
Labels: enhancement

#2558 Fixed issue in RDA cfg grabbing
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug

#2549 Better sync UI
  angr/knowledge_plugins/sync/sync_manager.py
Labels: feature

#2570 Handle void simtypefunction in _with_arch properly
  angr/sim_type.py
Labels: bug

#2533 CFGFast: Make sure project.entry is always the first in the list.
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: bug

#2521 Proximity graph.
  angr/analyses/__init__.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/proximity_graph.py
  tests/test_proximitygraph.py
Labels: feature
