Repository angr/angr, pull requests merged in 2021-02, with the labels that each got.

#2511 Propagator: _handle_Call() should store a Top to ret_expr.
  angr/analyses/propagator/engine_ail.py
Labels: bug

#2513 Clinic: Unify SSA register and stack variables.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/sim_variable.py
  tests/test_decompiler.py
Labels: feature

#2512 Let veritesting and explorer work together.
  angr/sim_manager.py
Labels: enhancement

#2515 Fix an issue related to CFGEmulated generated using base graph, and add a test case.
  angr/analyses/cfg/cfg_emulated.py
  tests/test_cfgemulated.py
Labels: bug

#2530 StructuredCodeGen: Print integers as negative numbers if possible.
  angr/analyses/decompiler/structured_codegen.py
Labels: enhancement

#2531 StructuredCodeGen: Support regenerating decompilation output.
  angr/analyses/decompiler/structured_codegen.py
Labels: feature

#2534 Optimize CFGSliceToSink.path_between().
  angr/analyses/cfg_slice_to_sink/cfg_slice_to_sink.py
Labels: enhancement

#2532 changed _desc of memory/register read/write actions to easily identify their behavior
  angr/state_plugins/sim_action.py
  angr/state_plugins/sim_event.py
  angr/storage/memory_mixins/regioned_memory/static_find_mixin.py
  tests/analyses/reaching_definitions/test_rd_state.py
Labels: enhancement
