Repository angr/angr, pull requests merged in 2021-08, with the labels that each got.

#2847 VRA: Reduce memory usage by eliminating unnecessary function refs.
  angr/analyses/variable_recovery/variable_recovery.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: enhancement

#2849 VRA: Reduce memory footprint - strike 2.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/forward_analysis/forward_analysis.py
  angr/analyses/reaching_definitions/__init__.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/storage/memory_mixins/convenient_mappings_mixin.py
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/cooperation.py
  angr/storage/memory_mixins/paged_memory/pages/list_page.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
  angr/utils/cowdict.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: enhancement

#2859 CFunction: Handle cases where the variable name is a substring of the type string.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#2863 Blade: Allow slicing across calls. Add a jump table resolving test case.
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/blade.py
  angr/engines/light/engine.py
  tests/test_jumptables.py
Labels: enhancement

#2864 SPTracker: Improve robustness for non-function-start dangling blocks without predecessors.
  angr/analyses/stack_pointer_tracker.py
Labels: enhancement

#2854 Fix merged_to calculation in ultra_page.
  angr/storage/memory_mixins/paged_memory/pages/ultra_page.py
  tests/test_memory_merge.py
Labels: bug

#2869 UltraPage: Do not ignore annotations on BVVs.
  angr/storage/memory_mixins/paged_memory/pages/ultra_page.py
Labels: bug

#2868 UltraPage: Fix an off-by-one error in store().
  angr/storage/memory_mixins/paged_memory/pages/ultra_page.py
Labels: bug

#2870 CallSiteMaker: Do not force-add a return value for each function call.
  angr/analyses/decompiler/callsite_maker.py
  tests/test_decompiler.py
Labels: enhancement

#2871 Structurer: Fix missing conditionals caused by EmptyNodeRemover creating new SequenceNodes.
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#2872 Propagator: Handle concatenation and zero-extentions in AIL engine.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  tests/test_decompiler.py
Labels: enhancement

#2873 Structurer: Fix switch-case failures with fully folded jump table entries.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#2874 FormatParser: Support \.\d+ as a flag.
  angr/procedures/stubs/format_parser.py
Labels: feature

#2875 Decompiler: Fix missing stack arguments.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/prop_value.py
  angr/analyses/propagator/propagator.py
  angr/errors.py
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
  tests/test_decompiler.py
Labels: bug

#2876 Decompiler: Avoid self-replacing Load expressions.
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
Labels: bug

#2877 AILSimplifier: Fix an issue in unify_variables() that may cause missing variables.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  tests/test_decompiler.py
Labels: bug

#2880 Structurer: Fix a case where certain conditions are missing.
  angr/analyses/decompiler/empty_node_remover.py
Labels: bug

#2883 CFGFast: ARM mode prologues must start at 4-aligned positions.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#2884 JumptableResolver: Filter jump targets based on instruction alignment.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: enhancement
