Repository angr/angr, pull requests merged in 2022-07, with the labels that each got.

#3419 Add the function declaration for execle.
  angr/procedures/definitions/glibc.py
Labels: bug

#3420 JobInfo: Fix __eq__ check.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/forward_analysis/job_info.py
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: bug

#3421 LiveDefinitions: Do not crash if we fail to convert arguments to stack offsets.
  angr/knowledge_plugins/key_definitions/live_definitions.py
Labels: bug

#3422 Add SimProcedure access.
  angr/procedures/linux_kernel/access.py
Labels: feature

#3426 Lazy import sympy.
  angr/analyses/decompiler/condition_processor.py
  angr/utils/__init__.py
  angr/utils/lazy_import.py
Labels: enhancement

#3427 MVPagedMemory: Fix cross-page unaligned writes.
  angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/cooperation.py
  tests/test_memory.py
Labels: bug

#3436 RegionedMemoryMixin: Fix an exception caused by VSA model resolution failures.
  angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py
Labels: bug

#3444 Propagator: Loosen the stack store outdate requirement.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
Labels: enhancement

#3448 CFGFast: Fix incorrect unicode string detection.
  angr/analyses/cfg/cfg_fast.py
  tests/test_decompiler.py
Labels: bug

#3381 Fix some type errors
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/storage/memory_mixins/regioned_memory/regioned_memory_mixin.py
Labels: bug

#3450 CascadingIfsRemover: Handle true nodes without a SequenceNode.
  angr/analyses/decompiler/region_simplifiers/cascading_ifs.py
Labels: bug

#3451 Add a peephole optimization that converts bitwise-ors to logical-ors.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/bitwise_or_to_logical_or.py
  angr/analyses/propagator/engine_ail.py
  tests/test_propagator_loops.py
Labels: enhancement

#3452 Support more variants of modulo optimizations in compilers.
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div_const_mul_const.py
  angr/analyses/decompiler/peephole_optimizations/conv_const_mull_a_shift.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: enhancement

#3449 Added Chroot SimProcedures
  angr/procedures/definitions/linux_kernel.py
  angr/procedures/posix/chroot.py
  tests/test_chroot.py
Labels: feature

#3453 JumptableResolver: Force gp register values for MIPS32 binaries.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: enhancement

#3454 MipsElfFastResolver: Implement fast paths.
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
Labels: enhancement

#3455 switch_extract_cmp_bounds: Add a missing type check.
  angr/analyses/decompiler/utils.py
Labels: bug

#3456 Fix issues preventing angr from resolving string refs for certain MIPS32 binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/const_derefs.py
  angr/analyses/decompiler/optimization_passes/register_save_area_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  tests/test_decompiler.py
Labels: bug

#3461 Avoid doing lazy import when pyinstaller is in-place.
  angr/analyses/decompiler/condition_processor.py
  angr/utils/__init__.py
  angr/utils/env.py
Labels: bug

#3460 Fix parsing of values of SimStructValue
  angr/calling_conventions.py
Labels: bug
