Repository angr/angr, pull requests merged in 2022-01, with the labels that each got.

#3046 VariableManager: Remove per-block variable dict.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: refactor

#3048 VRA: Avoid converting sizes for constants from strings.
  angr/analyses/variable_recovery/engine_vex.py
  angr/engines/vex/claripy/datalayer.py
Labels: enhancement

#3047 VRA: Add some missing handlers.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/engines/light/engine.py
Labels: enhancement

#3050 CCA: Support function size threshold.
  angr/analyses/complete_calling_conventions.py
Labels: feature

#3045 Pages: Use HistoryTrackingMixin to speed up page merging.
  angr/storage/memory_mixins/paged_memory/pages/__init__.py
  angr/storage/memory_mixins/paged_memory/pages/history_tracking_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/list_page.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
  angr/storage/memory_mixins/paged_memory/pages/refcount_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/ultra_page.py
  tests/test_memory_merge.py
Labels: feature

#3055 Static analyses: Sleep less and work more.
  angr/analyses/analysis.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: enhancement

#3056 FunctionManager: Record addresses of all recovered functions.
  angr/knowledge_plugins/functions/function_manager.py
Labels: enhancement

#3057 CFGFast: Fix several corner cases in function returning detection.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  tests/test_cfgfast.py
Labels: bug

#3060 SimCC.next_arg(): Handle BOT arguments.
  angr/calling_conventions.py
Labels: enhancement

#3061 CFGModel.get_any_node(): Correctly handle real addresses in THUMB mode.
  angr/knowledge_plugins/cfg/cfg_manager.py
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: bug

#3062 StackPointerTracker: Initialize FunctionGraphVisitor with normalized functions.
  angr/analyses/stack_pointer_tracker.py
Labels: bug

#3063 CFGFast: A more complete cascading block removal upon decoding failures.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#3065 CFGFast: Recognize ifuncs on ARM THUMB binaries.
  angr/analyses/cfg/cfg_arch_options.py
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#3067 CFGBase: Add one more THUMB nop instruction.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#3068 CFGFast: Do not match against bx lr in strings heuristics.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#3069 CFGFast: Copy outside transitions when breaking up CFGNodes.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#3064 CFGBase: Support merging more types of incomplete functions.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#3066 Tail-call detection: Reduce false positives and limit analysis scope.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#3073 CFGFast: Avoid overlapping THUMB and ARM nodes.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#3074 CCA: Match function prototype based on function name.
  angr/analyses/calling_convention.py
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#3079 VariableManager: Only reuse phi vars for variables created in the same block.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: bug

#3075 Decompiler: A new peephole optimizer: eager evaluation.
  angr/analyses/decompiler/optimization_passes/const_derefs.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  tests/test_peephole_optimizations.py
Labels: feature

#3080 Multiple fixes in CCA, RDA, and other places.
  angr/analyses/calling_convention.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/key_definitions/tag.py
  angr/procedures/definitions/glibc.py
Labels: bug

#3078 Fix: Oneuse expr folder may cause missing assignments.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/sequence_walker.py
  tests/test_structurer.py
Labels: bug

#3077 Decompiler: Handle variables in externs.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: feature

#3076 Clinic: Adjust analysis order and add a new opt stage.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
Labels: enhancement

#3089 Structurer: Fix a crash when creating loop break nodes.
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#2981 Handle segment information when generating cfgnode
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: enhancement

#3082 added check that node is in list before calling remove
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: bug

#3099 Reassembler: Handle .init and .fini sections that new GCC creates.
  angr/analyses/reassembler.py
  tests/test_reassembler.py
Labels: enhancement
