Repository angr/angr, pull requests merged in 2022-04, with the labels that each got.

#3269 OneUseExprFolder: Implement missing cascading condition node handlers.
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
Labels: bug

#3272 parse_cpp_file: Catch CppParseError.
  angr/sim_type.py
Labels: bug

#3273 CondProc: Use .op as a fall back after .verbose_op.
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#3278 VFG: Do not raise an exception on multivalued calls.
  angr/analyses/vfg.py
Labels: bug

#3283 OneUseExpr: Fix an over folding issue.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
  tests/test_decompiler.py
Labels: bug

#3284 VFG: Fix the incorrect SimProcedure initialization.
  angr/analyses/vfg.py
Labels: bug

#3285 SimplifierAILEngine: Fix an over-propagation issue.
  angr/analyses/decompiler/optimization_passes/engine_base.py
Labels: bug

#3286 CCallRewriter: Implement more AMD64 ccalls rewriters.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#2889 fix over-filtering in arm_thumb_filter_jump_successors
  angr/analyses/cfg/cfg_base.py
Labels: bug, enhancement

#3296 Decompiler: Fix variable type reflowing for global variables.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/base.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typeconsts.py
Labels: bug

#3297 SimType: Populate extra_types with predefined types.
  angr/sim_type.py
Labels: bug

#3304 Structurer: Do not remove conditional jumps when structuring sequences.
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#3303 JumptableResolving: Fix potential infinite jumptable resolving issues.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/blade.py
  angr/exploration_techniques/__init__.py
  angr/exploration_techniques/local_loop_seer.py
Labels: bug

#3305 Decompiler: Implement variable narrowing.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/code_location.py
  angr/knowledge_plugins/key_definitions/rd_model.py
  angr/knowledge_plugins/key_definitions/uses.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_decompiler.py
  tests/test_propagator_loops.py
Labels: feature

#3306 AILSimplifier: Fix an over-simplification issue in unify_local_variables
  angr/analyses/decompiler/ail_simplifier.py
  angr/knowledge_plugins/key_definitions/uses.py
  tests/test_decompiler.py
Labels: bug

#3307 StructuredCodeGen: Fix a missing base address type in Load handling.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug
