Repository angr/angr, pull requests merged in 2022-06, with the labels that each got.

#3385 MultiValues: Fix a bug leading to inconsistent slot sizes.
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  tests/test_multivalues.py
Labels: bug

#3386 VariableManager: More resilient to missing Phi variables.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: enhancement

#3388 CCA: Ignore binary name when finding declarations for SimProcedures.
  angr/analyses/calling_convention.py
Labels: bug

#3389 DepGraph: Fix a crash if the edge data is None when generating closures.
  angr/analyses/reaching_definitions/dep_graph.py
Labels: bug

#3390 MVListPage: Correctly update sinkhole.
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: bug

#3387 Fix the division simplifier for signed multiplications. Also fix a bug in propagator.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/propagator/propagator.py
  tests/test_decompiler.py
Labels: bug

#3393 RegionSimplifier: Remove empty nodes at the end of the run.
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
Labels: enhancement

#3394 VariableManager: Fix duplicated phi variables upon re-decompiling.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: bug

#3392 Clinic: Unbreak must-struct.
  angr/analyses/decompiler/clinic.py
Labels: bug

#3395 Decompiler: Support creating ternary expressions.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/ite_expr_converter.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/region_walker.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/angrdb/models.py
  angr/angrdb/serializers/structured_code.py
  tests/test_cfgfast.py
Labels: feature

#3398 JumpTableResolver: Set up gp before emulation.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/test_jumptables.py
Labels: bug

#3400 RegionIdentifier: Remove unstructurable loop heads.
  angr/analyses/cfg/cfg_utils.py
  angr/analyses/decompiler/region_identifier.py
  angr/utils/graph.py
  tests/test_decompiler.py
Labels: bug

#3412 Fix memory_write_length is None during BPs
  angr/engines/vex/heavy/heavy.py
Labels: bug
