Repository angr/angr, pull requests merged in 2022-11, with the labels that each got.

#3597 SimLinux: Fix uninitialized high 32 bits of the argc on stack.
  angr/simos/linux.py
Labels: bug

#3600 Disassembly: Fix offset parsing issue in MIPS instructions.
  angr/analyses/disassembly.py
  tests/test_disassembly.py
Labels: bug

#3590 Convert CuteHandler to CuteFormatter
  angr/misc/loggers.py
Labels: bug

#3592 3591 logging is impossible to read on a black terminal
  angr/misc/loggers.py
Labels: enhancement

#3605 LightVEXMixin: Fix the condition of _handle_CmpLT.
  angr/engines/light/engine.py
Labels: bug

#3607 [MIPS] Don't set gp if the value isn't resolved
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#3594 3593 log level colors
  angr/misc/ansi.py
  angr/misc/loggers.py
Labels: feature

#3610 IfElseFlattener: Fix a node loss for else nodes in switch-cases. Add a test case.
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: bug

#3611 StructuredCodeGen: Output while (true) instead of while (True).
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3612 IfElseFlattener: Swap processing order to avoid referencing unknown parent nodes.
  angr/analyses/decompiler/region_simplifiers/ifelse.py
Labels: bug

#3620 Print exceptions during logging
  angr/misc/loggers.py
Labels: bug

#3615 A Phoenix-inspired structuring algorithm
  angr/analyses/cfg/cfg_utils.py
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/jumptable_entry_condition_rewriter.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/ite_expr_converter.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifiers/cascading_cond_transformer.py
  angr/analyses/decompiler/region_simplifiers/cascading_ifs.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/goto.py
  angr/analyses/decompiler/region_simplifiers/if_.py
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/region_simplifiers/loop.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structuring/__init__.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  angr/analyses/decompiler/utils.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/gotos.py
  angr/utils/graph.py
  tests/test_decompiler.py
  tests/test_propagator_loops.py
  tests/test_structurer.py
Labels: enhancement

#3634 Phoenix: Add a while-true-cond-break graph schema.
  angr/analyses/cfg/cfg_utils.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/utils/graph.py
  tests/test_decompiler.py
Labels: bug

#3638 Refactor insert_node() to make it more readable.
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/utils.py
Labels: refactor

#3637 JumptableResolver: Perform constant propagation before attempting resolves.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/propagator/propagator.py
  angr/knowledge_plugins/functions/function.py
  angr/slicer.py
  tests/test_jumptables.py
Labels: feature

#3639 Phoenix: Fix the duplication of default cases in switch-cases.
  angr/analyses/decompiler/structuring/phoenix.py
  tests/test_decompiler.py
Labels: bug

#3641 GotoSimplifier: Fix the missing successor when processing else nodes in CascadingConditionNodes.
  angr/analyses/decompiler/region_simplifiers/goto.py
Labels: bug

#3640 Phoenix: Properly support compound boolean conditions.
  angr/analyses/decompiler/region_simplifiers/cascading_ifs.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: feature

#3642 Phoenix: Fix an infinite loop when structuring jump tables with cases going to the loop headers.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: bug

#3645 Fix an infinite loop in CStructuredCodeGenerator._access.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3646 ConditionProcessor: Fix conversion of single-bit boolean AIL consts.
  angr/analyses/decompiler/condition_processor.py
Labels: bug
