Repository angr/angr, pull requests merged in 2022-03, with the labels that each got.

#3161 Disassembly: Do not mark 40 as prefix in 40(gp) for MIPS64.
  angr/analyses/disassembly.py
Labels: bug

#3159 CFGFast: MIPS64: Specify gp and t9.
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  angr/factory.py
  tests/test_cfgfast.py
Labels: feature

#3162 Fix two issues in expression folder that lead to missing expressions.
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/sim_variable.py
  tests/test_decompiler.py
Labels: bug

#3163 CCallRewriter: Support amd64g carry flags for add.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#3164 Propagator: Fix initial register setup for MIPS64.
  angr/analyses/propagator/propagator.py
Labels: bug

#3165 Decompiler: Correctly resolve and display string references in i386 GCC PIEs.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/x86_gcc_getpc_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  tests/test_cfgfast.py
  tests/test_decompiler.py
Labels: feature

#3168 Multiprocessing support for CompleteCallingConventions.
  angr/analyses/analysis.py
  angr/analyses/complete_calling_conventions.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_calling_convention_analysis.py
Labels: feature

#3169 Fix SimUnicorn compilation under Windows.
  native/angr_native.def
  native/sim_unicorn.cpp
Labels: bug

#3170 CompleteCallingConventions: Support prioritizing functions.
  angr/analyses/complete_calling_conventions.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: feature

#3171 Add support for GCC-generated X86-PIE binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/reassembler.py
  angr/procedures/glibc/__libc_start_main.py
  angr/procedures/posix/pthread.py
  angr/sim_procedure.py
  tests/test_reassembler.py
Labels: feature

#3173 VFG: Add a test case to demonstrate how to resolve indirect calls.
  angr/analyses/vfg.py
  tests/test_vfg.py
Labels: feature

#3174 ProgressBar: Display status text.
  angr/analyses/analysis.py
Labels: enhancement

#3175 ConditionProcessor: adds cutoffs to simplify_condition().
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#3176 Structurer: Be less strict about switch-case recognition.
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structurer.py
  tests/test_decompiler.py
Labels: bug

#3181 Propagator: Fix an over-propagation for call arguments.
  angr/analyses/propagator/engine_ail.py
  tests/test_decompiler.py
Labels: bug

#3183 Adapt to progressbar2 changes.
  angr/analyses/analysis.py
Labels: enhancement

#3184 MipsElfFastResolver: Handle DEFAULT_STATEMENT. Close #3154.
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
Labels: bug

#3189 ForwardAnalysis: Converge faster on cyclic graphs.
  angr/analyses/forward_analysis/visitors/function_graph.py
  angr/analyses/forward_analysis/visitors/graph.py
  tests/analyses/reaching_definitions/test_subject.py
Labels: enhancement

#3191 Add a few more AMD64 ccall rewriters for CmpEQ, CmpLE, and CmpLT.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#3192 Fix a statement ID error in CallSiteMaker.
  angr/analyses/decompiler/callsite_maker.py
Labels: bug

#3188 CFGFast: Add DYNAMIC_RET. Understand error() sometimes does not return.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/complete_calling_conventions.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/libc/err.py
  angr/procedures/libc/error.py
  angr/sim_procedure.py
  tests/test_cfgfast.py
  tests/test_function_manager.py
  tests/test_jumptables.py
Labels: feature

#3201 CCA: Force spawn mode on MacOS for Python<3.8.
  angr/analyses/complete_calling_conventions.py
  angr/utils/mp.py
Labels: bug

#3200 Make the sysinfo system call indicate success
  angr/procedures/linux_kernel/sysinfo.py
Labels: bug

#3204 Decompiler: Fix nested loops identification. Reimplement switch-case handling.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/jumptable_entry_condition_rewriter.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
  tests/test_decompiler.py
  tests/test_propagator_loops.py
Labels: bug

#3211 StructuredCodeGen: No more Nones in Load().
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: enhancement

#3218 VRA: Allow assigning artificial registers to variables.
  angr/analyses/variable_recovery/engine_base.py
Labels: enhancement

#3223 ConditionProcessor: Use variable names for Load and Register when available.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#3224 AILSimplifier: Revive expression folding.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/knowledge_plugins/key_definitions/uses.py
Labels: bug

#3225 EagerReturns: Fix issues with duplicating blocks for more than two levels.
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/structurer.py
  angr/analyses/decompiler/structurer_nodes.py
Labels: bug

#3226 Propagator: Aggressively remove tmps by replacing them with equivalent registers.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  tests/test_propagator_loops.py
Labels: enhancement

#3228 Make Block and Function pickle slightly faster.
  angr/analyses/calling_convention.py
  angr/block.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
Labels: enhancement

#3229 Flirt: Add support for ARM THUMB mode.
  angr/analyses/flirt.py
Labels: bug

#3237 Labels: Ignore $a, $d, and $t on ARM binaries.
  angr/knowledge_plugins/labels.py
Labels: feature

#3234 StructuredCodeGen: Support div, mod, and intrinsic functions.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: feature

#3230 Clinic: Only ensure calling conventions of the related functions are recovered
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/clinic.py
  tests/test_decompiler.py
Labels: feature

#3231 CondProc: Remove the incorrect assumption.
  angr/analyses/decompiler/condition_processor.py
  tests/test_decompiler.py
Labels: bug

#3232 Various creations and improvements of decompilation optimizations.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/a_div_const_add_a_mul_n_div_const.py
  angr/analyses/decompiler/peephole_optimizations/a_mul_const_div_shr_const.py
  angr/analyses/decompiler/peephole_optimizations/a_shl_const_sub_a.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div_const_mul_const.py
  angr/analyses/decompiler/peephole_optimizations/bswap.py
  angr/analyses/decompiler/peephole_optimizations/conv_const_mull_a_shift.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/engines/light/engine.py
Labels: enhancement

#3235 Fix how FlirtAnalysis matches strings.
  angr/analyses/flirt.py
Labels: enhancement

#3236 OutdatedDefinitionWalker: Be less strict about preceding stores.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
Labels: enhancement

#3233 Fix an incorrect fork detection in EagerReturns.
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/structurer.py
Labels: bug

#3243 add a func_queue.get() timeout for CompleteCallingConvention workers to avoid deadlock race condition
  angr/analyses/complete_calling_conventions.py
Labels: bug

#3242 Refactor names and descriptions of optimization passes
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/const_derefs.py
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/mod_simplifier.py
  angr/analyses/decompiler/optimization_passes/multi_simplifier.py
  angr/analyses/decompiler/optimization_passes/register_save_area_simplifier.py
  angr/analyses/decompiler/optimization_passes/ret_addr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/optimization_passes/x86_gcc_getpc_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/a_div_const_add_a_mul_n_div_const.py
  angr/analyses/decompiler/peephole_optimizations/a_mul_const_div_shr_const.py
  angr/analyses/decompiler/peephole_optimizations/a_shl_const_sub_a.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div_const_mul_const.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_sub_n.py
  angr/analyses/decompiler/peephole_optimizations/base.py
  angr/analyses/decompiler/peephole_optimizations/basepointeroffset_add_n.py
  angr/analyses/decompiler/peephole_optimizations/basepointeroffset_and_mask.py
  angr/analyses/decompiler/peephole_optimizations/bool_expr_xor_1.py
  angr/analyses/decompiler/peephole_optimizations/bswap.py
  angr/analyses/decompiler/peephole_optimizations/coalesce_same_cascading_ifs.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/peephole_optimizations/conv_a_sub0_shr_and.py
  angr/analyses/decompiler/peephole_optimizations/conv_const_mull_a_shift.py
  angr/analyses/decompiler/peephole_optimizations/conv_shl_shr.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/decompiler/peephole_optimizations/extended_byte_and_mask.py
  angr/analyses/decompiler/peephole_optimizations/one_sub_bool.py
  angr/analyses/decompiler/peephole_optimizations/remove_cascading_conversions.py
  angr/analyses/decompiler/peephole_optimizations/remove_empty_if_body.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_bitmasks.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_conversions.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_ite_branch.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_nots.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_shifts.py
  angr/analyses/decompiler/peephole_optimizations/rewrite_mips_gp_loads.py
  angr/analyses/decompiler/peephole_optimizations/simplify_pc_relative_loads.py
  angr/analyses/decompiler/peephole_optimizations/single_bit_xor.py
Labels: refactor

#3244 Add local_types to decompilation cache; render local types in generated C
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/angrdb/serializers/structured_code.py
  angr/knowledge_plugins/structured_code/manager.py
Labels: feature

#3248 Clinic: Process non-constant global variable accesses.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3245 unify_local_variables: Detect unmatched def-use sizes.
  angr/analyses/decompiler/ail_simplifier.py
  angr/knowledge_plugins/key_definitions/uses.py
Labels: bug

#3247 Assign default types to BOT-type variables after decompilation.
  angr/analyses/decompiler/clinic.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/sim_variable.py
Labels: enhancement

#3246 Rework variable creation and pretty-printing in StructuredCodeGen.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_decompiler.py
Labels: bug

#3249 StructuredCodeGen: Add option to show function externs
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: feature

#3257 CFGFast: Fix a bug that causes fakeret edges being confirmed prematurely.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#3255 Unbreak Typehoon. Fix various issues with decompiler.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/stack_pointer_tracker.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  tests/test_typehoon.py
Labels: bug, enhancement

#3259 Only enable Shift/Xor code tagging on x86 and amd64 arches.
  angr/analyses/code_tagging.py
Labels: feature

#3260 Typehoon: Fix a supertype confusion.
  angr/analyses/typehoon/simple_solver.py
Labels: bug

#3261 Typehoon: Support nested global structs.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: feature

#3263 CFGFast: Allow users to not skip unmapped addresses.
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#3264 Enable FLIRT-based function prototype matching for static binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/flirt.py
  angr/knowledge_plugins/functions/function.py
  tests/test_flirt.py
Labels: feature

#3265 CodeGen: Adding types into the node2pos mapping.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: feature

#3266 CFG: Allow cross-segment/section functions if skip_unmapped_addrs is False.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: feature

#3268 CodeGen: Add a missing type cast when variable sizes don't match.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug
