Repository angr/angr, pull requests merged in 2022-12, with the labels that each got.

#3649 Mark _exit and _Exit as aliases to exit.
  angr/procedures/definitions/glibc.py
Labels: enhancement

#3650 Phoenix: Fix the overly strict condition for if-then matching.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/test_decompiler.py
Labels: bug

#3651 Decompiler: Correctly decompile tail-jumps as calls.
  angr/analyses/decompiler/clinic.py
  angr/analyses/reaching_definitions/engine_ail.py
  tests/test_decompiler.py
Labels: enhancement

#3652 Phoenix: Ensure graph edges exist before removing in cyclic refinement.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3653 Phoenix: Fix a crash caused by empty nodes in MultiNode instances.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3655 StructuredCodeGen: Guess function argument types when they are machine-word-size ints.
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: enhancement

#3658 CCallRewriter: Support __CFADD__ for AMD64.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/decompiler/ccall_rewriters/rewriter_base.py
  tests/test_decompiler.py
Labels: enhancement

#3656 Fix several issues in structuring.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  tests/test_decompiler.py
Labels: bug

#3659 Use one byte as the extern symbol fallback size.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3657 EmptyNodeRemover: Do not remove empty-body loops.
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: bug

#3619 Correct block printing for ARM Thumb
  angr/block.py
Labels: bug

#3680 Fix non-docstring docstrings
  angr/procedures/linux_kernel/arm_user_helpers.py
  angr/procedures/win32/GetLastInputInfo.py
  angr/procedures/win32/GetProcessAffinityMask.py
  angr/state_plugins/trace_additions.py
  tests/test_project_resolve_simproc.py
Labels: enhancement

#3689 Improve decompiler
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/disassembly.py
Labels: enhancement

#3693 Callsite-specific function prototype recovery.
  angr/analyses/calling_convention.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/callsite_prototypes.py
  tests/test_calling_convention_analysis.py
  tests/test_decompiler.py
Labels: enhancement

#3694 Disassembly: Fix a mis-calculation when trimming THUMB blocks.
  angr/analyses/disassembly.py
  angr/block.py
Labels: bug

#3695 CCCA: Enforce function prototype recovery order in parallel mode.
  angr/analyses/complete_calling_conventions.py
Labels: bug

#3696 StructuredCodeGen: Fix incorrect conversion of 32-bit negative integers.
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: bug

#3697 Rename selfmodifying_code, fix the test case, and fix pp() for smc blocks.
  angr/analyses/disassembly.py
  angr/block.py
  angr/engines/pcode/lifter.py
  angr/engines/vex/heavy/heavy.py
  angr/engines/vex/lifter.py
  angr/project.py
  tests/test_self_modifying_code.py
Labels: bug, refactor

#3504 Add Call_String to ExternalCodelocation
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/external_codeloc.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/atoms.py
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
Labels: feature

#3556 Unify SimTypeArray and SimTypeFixedSizeArray
  angr/calling_conventions.py
  angr/sim_type.py
Labels: enhancement
