Repository angr/angr, pull requests merged in 2023-11, with the labels that each got.

#4256 Fix support for unicode strings embedded in code sections.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/sim_type.py
  tests/analyses/cfg/test_cfgfast.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4257 StructuredCodeGen: Fix highlighting failures for repeated function calls.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#4261 VEXIRSBScanner: Add some unhandled irops.
  angr/analyses/variable_recovery/irsb_scanner.py
Labels: enhancement

#4263 Fix modulo operation for invalid variables
  angr/engines/light/engine.py
Labels: bug

#4316 IAT Resolvers: Be more resilient against instructions without operands.
  angr/analyses/cfg/indirect_jump_resolvers/amd64_pe_iat.py
  angr/analyses/cfg/indirect_jump_resolvers/x86_pe_iat.py
Labels: bug

#4320 VariableManager: Faster input_variables().
  angr/knowledge_plugins/variables/variable_manager.py
Labels: refactor

#4321 VariableManager: Add an identifier-to-variable mapping.
  angr/knowledge_plugins/variables/variable_manager.py
Labels: refactor

#4322 VRA: Use a single instance of TypeVariables to save merging time.
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
Labels: enhancement, refactor

#4323 KeyedRegion: Add fast paths for _store().
  angr/keyed_region.py
Labels: enhancement, refactor

#4327 Liveness: Use a more compact store.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/rd_initializer.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/liveness.py
  angr/knowledge_plugins/key_definitions/rd_model.py
Labels: refactor

#4330 RDA: Support loading definitions without loading values.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/function_handler.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/storage/memory_mixins/__init__.py
  angr/storage/memory_mixins/paged_memory/paged_memory_multivalue_mixin.py
Labels: refactor

#4332 MVListPage: Estimate changed bytes using the history tracking mixin.
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
Labels: enhancement

#4339 append_scc: Add a panic mode for faster convergence.
  angr/analyses/complete_calling_conventions.py
  angr/utils/graph.py
Labels: enhancement

#4341 update Function.string_references() to use modern CFG API
  angr/knowledge_plugins/functions/function.py
  tests/analyses/cfg/test_cfgemulated.py
Labels: enhancement

#4340 Fix some logic bugs in MultiValues
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  tests/storage/test_multivalues.py
Labels: bug

#4353 Proximity Graph: Condense and remove blank nodes
  angr/analyses/proximity_graph.py
Labels: bug

#4357 fix hashing of SimTypeFunction
  angr/sim_type.py
Labels: bug

#4359 CFGFast: Improve bp-as-gpr detection.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#4360 Improved Windows PE stack canary removal logic.
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
Labels: enhancement

#4366 WinStackCanarySimplifier: Be less strict about sub-calls.
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
Labels: enhancement

#4367 ITERegionConverter: Check None before accessing .value.
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#4365 Decompiler: Outline strcpy.
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/base.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/peephole_optimizations/inlined_strcpy.py
  angr/analyses/decompiler/peephole_optimizations/inlined_strcpy_consolidation.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/utils.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/custom_strings.py
Labels: enhancement

#4361 Add CLI access to the angr decompiler
  angr/__main__.py
  angr/analyses/decompiler/utils.py
  setup.cfg
Labels: enhancement

#4369 CFGFast: Remove spurious edges generated by lock xxx instructions.
  angr/analyses/cfg/cfg_fast.py
  tests/analyses/cfg/test_cfgfast.py
Labels: bug

#4179 IfElseFlattener: Do not de-else or swap if both branches terminate.
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4372 fold_call_exprs: Ensure the propagation destination is not overwritten.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug
