Repository angr/angr, pull requests merged in 2023-09, with the labels that each got.

#4124 Phoenix: Fix a bug causing incorrect excessive goto statements.
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: bug

#4126 Fix a non-determinism in quasi topological sort with SCCs.
  angr/utils/graph.py
Labels: bug

#4127 Blacken glibc definitions.
  angr/procedures/definitions/glibc.py
Labels: refactor

#4128 Add prototype for __sprintf_chk.
  angr/procedures/definitions/glibc.py
Labels: enhancement

#4145 Fix: rewrite_ite_expression use the same address for different block
  angr/analyses/decompiler/clinic.py
Labels: bug

#4147 Decompiler: Default to Phoenix when structuring algorithm is not specified.
  angr/analyses/decompiler/decompiler.py
Labels: enhancement

#4148 Phoenix: Avoid creating MultiStatementExpression without statements.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#4151 CCA: Implement variadic function identification for AMD64 SysV. Also fix a CFG bug.
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_base.py
  tests/analyses/test_calling_convention_analysis.py
Labels: bug, enhancement

#4152 Clinic: Re-enable stack-based function arg elimination.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4153 Phoenix: Add a switch for enabling MultiStatementExpressions.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: enhancement

#4163 CIFElse: Fix the omit_braces logic.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#4165 RegionIdentifier: Find loop headers again after abstracting a loop.
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#4164 rewrite_ite_expressions: Do not rewrite jump table heads.
  angr/analyses/decompiler/clinic.py
Labels: bug

#4177 Multiple fixes related to MultiStatementExpression.
  angr/analyses/decompiler/call_counter.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#4178 Clinic: Link variables to ITE.iffalse.
  angr/analyses/decompiler/clinic.py
Labels: bug

#4182 Callable: allow easy update to state options.
  angr/callable.py
  angr/factory.py
Labels: enhancement

#4180 Phoenix: A new schema before resorting to nat-loops.
  angr/analyses/decompiler/region_simplifiers/ifelse.py
  angr/analyses/decompiler/region_simplifiers/loop.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4181 Make CC and DEFAULT_CC platform-aware.
  angr/__init__.py
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/optimization_passes/ret_addr_save_simplifier.py
  angr/analyses/identifier/custom_callable.py
  angr/analyses/propagator/engine_vex.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/callable.py
  angr/calling_conventions.py
  angr/engines/pcode/engine.py
  angr/exploration_techniques/director.py
  angr/factory.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
  angr/procedures/glibc/__libc_start_main.py
  angr/procedures/java_jni/__init__.py
  angr/procedures/libc/error.py
  angr/project.py
  angr/sim_procedure.py
  angr/simos/javavm.py
  angr/simos/simos.py
  tests/analyses/test_calling_convention_analysis.py
  tests/knowledge_plugins/functions/test_function2.py
  tests/knowledge_plugins/functions/test_prototypes.py
  tests/sim/test_stack_alignment.py
Labels: enhancement

#4190 Decompiler: Rewrite one more ccall. Improve expression replacer.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4191 Propagator: Fix an over-propagation in AIL.
  angr/analyses/propagator/propagator.py
  angr/knowledge_plugins/propagations/states.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4192 CondProc: Optimize negated conjunctions and disjunctions.
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/invert_negated_logical_conjuction_disjunction.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4195 Support simplifying fully lowered switches.
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/region_simplifiers/switch_cluster_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4196 RDA: Truncate call exprs if needed.
  angr/analyses/reaching_definitions/engine_ail.py
Labels: bug

#4197 ConstDerefs: Catch KeyErrors caused by insufficient bytes to read.
  angr/analyses/decompiler/optimization_passes/const_derefs.py
Labels: bug

#4198 Fix two crashes caused by unexpected FP constants.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: bug

#4199 LoweredSwitchSimplifier: Support simplifying binary trees.
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/storage/memory_mixins/multi_value_merger_mixin.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4202 Add size fixers to amd64 ccall rewriters.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: bug

#4200 Make lowered switch simplifier work when running after eager returns.
  angr/analyses/decompiler/optimization_passes/const_derefs.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/coalesce_same_cascading_ifs.py
  angr/analyses/decompiler/peephole_optimizations/remove_empty_if_body.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4203 GraphRegion: Do not re-add replaced regions to parent regions during replacement.
  angr/analyses/decompiler/graph_region.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4204 Phoenix: Do not manipulate the graph before bailing out.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#4205 LoweredSwitchSimplifier: add the missing in-degree check.
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
Labels: bug

#4207 CCA: Sort call sites to eliminate a source of non-determinism.
  angr/analyses/calling_convention.py
Labels: enhancement

#4208 ConstDerefs: Support simplifying call targets and call exprs.
  angr/analyses/decompiler/optimization_passes/const_derefs.py
Labels: enhancement

#4212 CCA: Use platform when retrieving default CCs.
  angr/analyses/calling_convention.py
Labels: bug, enhancement

#4210 EagerReturns: Enable it for all arches and all platforms.
  angr/analyses/decompiler/optimization_passes/eager_returns.py
Labels: enhancement

#4209 Add a Windows PE stack canary simplifier opt pass.
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
Labels: enhancement

#4211 CCA: Set default function return type to void instead of None.
  angr/analyses/calling_convention.py
  tests/analyses/test_calling_convention_analysis.py
Labels: bug

#4213 AngrDb: Fix missing nodes in callgraphs after loading the db.
  angr/knowledge_plugins/functions/function_manager.py
  tests/serialization/test_db.py
Labels: bug
