Repository angr/angr, pull requests merged in 2023-07, with the labels that each got.

#4024 CFG: Support parsing regions out of Hex backend.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#4020 Enable incremental CFG recovery and updating
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/disassembly.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/block.py
  angr/engines/pcode/lifter.py
  angr/engines/vex/lifter.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/memory_data.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/patches.py
  tests/test_cfg_model.py
  tests/test_cfg_patching.py
  tests/test_cfgfast.py
  tests/test_patches.py
Labels: enhancement

#4025 Several fixes to enable CC detection for PCode-PPC.
  angr/analyses/calling_convention.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/register_save_area_simplifier.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/calling_conventions.py
  angr/engines/pcode/cc.py
  angr/knowledge_plugins/propagations/states.py
Labels: bug, enhancement

#4031 VRA: Implement the Mod handler for VEX engine.
  angr/analyses/variable_recovery/engine_vex.py
Labels: enhancement

#4011 Phoenix: Use post-ordering in last_resort_refinement.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/propagator/propagator.py
  angr/knowledge_plugins/propagations/states.py
  tests/test_decompiler.py
Labels: bug

#4051 Use a faster internal data structure for RDA.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/knowledge_plugins/key_definitions/liveness.py
  angr/knowledge_plugins/key_definitions/rd_model.py
  angr/utils/timing.py
Labels: enhancement
