Repository angr/angr, pull requests merged in 2023-05, with the labels that each got.

#3929 Clinic: Fix missing variables in duplicated blocks.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/peephole_optimizations/base.py
  angr/analyses/decompiler/peephole_optimizations/remove_noop_conversions.py
  angr/analyses/decompiler/peephole_optimizations/simplify_pc_relative_loads.py
  angr/analyses/decompiler/peephole_optimizations/single_bit_cond_to_boolexpr.py
  angr/analyses/decompiler/region_simplifiers/switch_expr_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/propagations/prop_value.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_decompiler.py
Labels: bug

#3931 CFGFast: Ignore functions created by dataref hints if their addresses have been analyzed.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#3933 MVMergerMixin: Merge into one value with many annotations when all values are the same.
  angr/storage/memory_mixins/multi_value_merger_mixin.py
Labels: enhancement

#3932 Support conditional returns in RDA and SPTracker.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/stack_pointer_tracker.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: enhancement

#3935 VRA: Pre-scan to determine narrowing targets to avoid changing immutable objects.
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/analyses/variable_recovery/irsb_scanner.py
  docs/api.rst
  tests/test_calling_convention_analysis.py
Labels: bug

#3937 VRA: VEXEngine: Ignore superfluous register reads in -O0 binaries.
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/analyses/variable_recovery/irsb_scanner.py
  tests/test_calling_convention_analysis.py
Labels: enhancement

#3939 Decompiler: Switch the default structuring algorithm to phoenix.
  angr/analyses/decompiler/decompilation_options.py
Labels: enhancement

#3938 VRA: AILEngine: Fix missing variables in duplicated blocks.
  angr/analyses/variable_recovery/engine_base.py
  tests/test_decompiler.py
Labels: bug

#3936 RDA: Redesigned function handler interfaces
  angr/analyses/analysis.py
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  angr/analyses/find_objects_static.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/__init__.py
  angr/analyses/reaching_definitions/dep_graph.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/external_codeloc.py
  angr/analyses/reaching_definitions/function_handler.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/calling_conventions.py
  angr/code_location.py
  angr/engines/light/engine.py
  angr/factory.py
  angr/knowledge_plugins/key_definitions/atoms.py
  angr/knowledge_plugins/key_definitions/definition.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/misc/plugins.py
  angr/misc/testing.py
  angr/procedures/definitions/__init__.py
  angr/project.py
  angr/sim_procedure.py
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/all_visited_blocks.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_visited_blocks.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_visited_blocks.pickle
  tests/analyses/reaching_definitions/test_rd_state.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
  tests/knowledge_plugins/key_definitions/test_atoms.py
  tests/test_decompiler.py
Labels: enhancement, refactor

#3941 Decompiler: Expose sequence node and local vars.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: feature

#3950 LiveDefinitions: Add shorthands for various definitions.
  angr/knowledge_plugins/key_definitions/live_definitions.py
Labels: refactor

#3951 Add Atom.reg and Atom.mem for Atom creation.
  angr/knowledge_plugins/key_definitions/atoms.py
  angr/knowledge_plugins/xrefs/xref.py
Labels: refactor

#3956 CFGFast: Keep functions for calls outside ranges.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#3957 RemoveRedundantITEComparisons: Support CmpNE.
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_ite_comparisons.py
Labels: enhancement

#3960 Fix local/external function detection for plt stubs
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#3961 RDA FunctionHandler: Add instead of subtract the sp diff after calls.
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#3963 Atom.from_argument: Fix SimStackArg conversion.
  angr/analyses/reaching_definitions/function_handler.py
  angr/knowledge_plugins/key_definitions/atoms.py
Labels: bug
