Repository angr/angr, pull requests merged in 2023-06, with the labels that each got.

#3995 CFGFast: Fix a missing indirect call check when indirect_calls_always_return is True.
  angr/analyses/cfg/cfg_fast.py
  tests/test_cfgfast.py
Labels: bug

#3996 EagerReturnsSimplifier: Avoid creating tons of case entries for the default case.
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/test_decompiler.py
Labels: enhancement

#3997 StructuredCodeGen: while(expr) always in the same line as the last curly-brace for do-while loops.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: enhancement

#4000 Xtensa-related resilience improvements for CFG and calling conventions.
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/engines/pcode/cc.py
Labels: enhancement

#4001 ExprOpSwapper: Fix swapping support for CmpEQ and CmpNE.
  angr/analyses/decompiler/optimization_passes/expr_op_swapper.py
  angr/analyses/decompiler/region_simplifiers/cascading_cond_transformer.py
Labels: bug

#4005 RDA: Reset uses dicts during state downsizing.
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
Labels: enhancement

#4004 Decompiler feature: remove redundant else scopes
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
  tests/test_structurer.py
Labels: feature
