Repository angr/angr, pull requests merged in 2023-01, with the labels that each got.

#3701 Decompiler: Fix support for partial register reads. Close #3698.
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/analyses/variable_recovery/variable_recovery.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_calling_convention_analysis.py
  tests/test_decompiler.py
Labels: bug

#3705 Structuring: Fix missing conditional continue nodes. Close #3699.
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: bug

#3707 SequenceWalker: Fix a failure caused by multiple parent-node insertions.
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/sequence_walker.py
Labels: bug

#3708 OptimizationPasses: Create a new category BEFORE_REGION_IDENTIFICATION.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/eager_returns.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/region_identifier.py
  tests/test_decompiler.py
Labels: bug

#3710 Phoenix: Fix over-matching when matching short-circuit compound patterns.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3709 Phoenix: Fix missing loops caused by loop refinement removing all headgoing edges.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3714 Phoenix: Fix over-matching in while-true-cond-break patterns.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: bug

#3717 Phoenix: Fix the overly strict while-true matching (and many other fixes).
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifiers/if_.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: bug

#3721 CCallRewriter: Add two more ccall rewriters.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#3720 AILSimplifier: Allow folding call expressions into conditions when Phoenix is in use.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/test_decompiler.py
Labels: enhancement

#3722 Decompiler: Support labels.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/jump_target_collector.py
  angr/analyses/decompiler/redundant_label_remover.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/utils.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/engines/light/engine.py
  tests/test_decompiler.py
Labels: enhancement

#3723 Propagator: Handle default function calling conventions in VEX engine.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/propagator/engine_vex.py
Labels: enhancement

#3724 error.dynamic_returns: Properly handle call blocks before the last one.
  angr/procedures/libc/error.py
Labels: bug

#3727 Phoenix: Fix an over-matching of if-then.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3729 Fix empty function prototype when full=True
  angr/sim_type.py
Labels: bug

#3726 RegionIdentifier: Refine loop nodes considering node hierarchy.
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/test_decompiler.py
Labels: enhancement

#3725 Carefully sort edges during last-resort refinement to reduce goto edges.
  angr/analyses/decompiler/structuring/phoenix.py
  tests/test_decompiler.py
Labels: enhancement

#3687 Fix fp rounding not to cut off high values
  angr/engines/vex/claripy/irop.py
Labels: bug

#3738 Phoenix._refine_cyclic: Replace old nodes in edge lists, and update nodes after they are no longer used.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3741 AILSimplifier: unify_local_variables missed a check for eq and use locations.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/reaching_definitions/rd_state.py
  tests/test_decompiler.py
Labels: bug

#3740 CCA: Include the predecessor of call sites when recovering prototypes if necessary.
  angr/analyses/calling_convention.py
  tests/test_decompiler.py
Labels: enhancement

#3682 `.pre-commit-config.yaml` added
  .pre-commit-config.yaml
  README.md
  angr/analyses/reaching_definitions/call_trace.py
  angr/analyses/reaching_definitions/external_codeloc.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/win32/GetLastInputInfo.py
  angr/sim_type.py
  angr/state_plugins/heap/heap_base.py
  angr/state_plugins/heap/heap_freelist.py
  angr/state_plugins/heap/heap_libc.py
  angr/state_plugins/inspect.py
  angr/state_plugins/view.py
  angr/storage/memory_object.py
  pyproject.toml
  tests/test_cfgemulated.py
  tests/test_ddg_memvar_addresses.py
  tests/test_slicing.py
  tests/test_variablerecovery.py
Labels: enhancement, add to docs

#3744 Propagator: Fix missing stack pointer setting in AIL mode.
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/tmpvar_finder.py
  tests/test_decompiler.py
Labels: bug

#3745 RegionIdentifier: Include all single-in-degree loop successor nodes in loops.
  angr/analyses/decompiler/region_identifier.py
  tests/test_decompiler.py
Labels: enhancement

#3746 RegionIdentifier: Fix missing end nodes in single-exit regions.
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3747 Propagator: Merging instead of overwriting existing replacements.
  angr/analyses/propagator/propagator.py
Labels: bug

#3748 Add two more ccall rewriter rules for AMD64.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#3750 Decompiler: Support reverting lowered switches.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  tests/test_decompiler.py
Labels: enhancement

#3749 Disassembly: add arm32 support
  angr/analyses/disassembly.py
  tests/test_disassembly.py
Labels: bug

#3751 Impose stricter checks for lowered switches. With other fixes.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_shifts_around_comparators.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
Labels: bug, enhancement

#3758 Fix smoketest CI in windows
  .github/workflows/smoketest.yml
Labels: bug

#3762 Fix race condition where the last function to be analyzed could be skipped when remaining_funcs is set to zero before being dequeued
  angr/analyses/complete_calling_conventions.py
Labels: bug

#3764 Clinic: Support calling convention analysis on AIL graphs.
  angr/analyses/calling_convention.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/empty_node_remover.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
Labels: enhancement

#3765 CFGFast: Enable dataref function hints. Fix #3759.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/test_cfgfast.py
Labels: bug

#3771 StackCanarySimplifier: Support reused call blocks.
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  tests/test_decompiler.py
Labels: enhancement
