Repository angr/angr, pull requests merged in 2023-08, with the labels that each got.

#4057 Commit bug from rare hash collision in _merge_values
  angr/storage/memory_mixins/multi_value_merger_mixin.py
Labels: bug

#4058 Clinic: Rewrite ITE expressions into if-else constructs.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/reaching_definitions/function_handler.py
  tests/test_decompiler.py
Labels: enhancement

#4060 RDA: kill_and_add_definitions() should respect endnesses of memory atoms.
  angr/analyses/reaching_definitions/function_handler.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  tests/analyses/reaching_definitions/test_function_handler.py
Labels: bug

#4061 CFGFast: Add all xrefs for data even when cross_references=False.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#4059 Fix zero division issues and flipped arguments in RDA DIV handling
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug

#4063 VRA: Unify variables after variable recovery.
  angr/analyses/decompiler/clinic.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: enhancement

#4064 Fix arm disassembly for multiple registers
  angr/analyses/disassembly.py
  tests/test_disassembly.py
Labels: bug

#4062 RDA: Add a new observation type exit.
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/knowledge_plugins/key_definitions/rd_model.py
Labels: enhancement

#4080 fix sigaction syscall return type (fixes #4079)
  angr/procedures/linux_kernel/sigaction.py
Labels: bug

#4086 StructuredCodeGen: Support displaying ints as chars.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: enhancement

#4089 RDA: Deprecate .xxx_definitions. Use .xxx instead.
  angr/analyses/calling_convention.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/find_objects_static.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/engine_vex.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  tests/analyses/reaching_definitions/test_rd_state.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: refactor

#4090 PoinerArithmeticFixer: Prefer v += 1 to v = &v[1].
  angr/analyses/decompiler/structured_codegen/c.py
  tests/test_decompiler.py
Labels: enhancement

#4091 FlipBooleanCmp: Walk the entire Sequence tree. Handle one more type.
  angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: enhancement

#4068 ConstMullAShift: Support simplifying expressions outside Convert.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py
  angr/analyses/decompiler/peephole_optimizations/conv_const_mull_a_shift.py
Labels: enhancement

#4095 CFGFast: Detect cases where r4 is set to a constant value in ARM binaries.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: enhancement

#4097 CondProc: Fix conflicts in calls used as conditions.
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#4108 Fix occasional IndexError when synchronizing concrete CLE
  angr/state_plugins/concrete.py
Labels: bug

#4109 Tidy stack addresses during decompilation.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/tidy_stack_addr.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/test_decompiler.py
Labels: enhancement

#4111 AngrDb: Exclude all cle TLS objects instead of only ELF TLS objects.
  angr/angrdb/serializers/loader.py
Labels: bug

#4113 SequenceWalker: Fix incorrect parent and label for handling loop bodies. Fixes #4082.
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/utils.py
  tests/test_decompiler.py
Labels: bug

#4114 EmptyNodeRemover: Support removing empty if-else scopes with AIL expression conditions.
  angr/analyses/decompiler/empty_node_remover.py
  tests/test_decompiler.py
Labels: bug

#4117 MultiValueMergerMixin: Limit the number of annotations and avoid OOM.
  angr/storage/memory_mixins/multi_value_merger_mixin.py
Labels: bug

#4120 EngineRDVEX: Make _shift_sar more robust.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: bug
