Repository angr/angr, pull requests merged in 2023-04, with the labels that each got.

#3893 Fix getenv on 32-bit architectures
  angr/procedures/posix/getenv.py
Labels: bug

#3894 VRA: Properly handle partial register overwrites.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/sim_type.py
  tests/test_calling_convention_analysis.py
Labels: bug, enhancement

#3900 add typehint for known plugins in AnalysesHub
  angr/analyses/analysis.py
  angr/project.py
Labels: refactor

#3911 Add a peephole optimization to handle shift-based signed divisions.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_conversions.py
  angr/analyses/decompiler/peephole_optimizations/sar_to_signed_div.py
  angr/analyses/decompiler/peephole_optimizations/single_bit_cond_to_boolexpr.py
  angr/analyses/decompiler/peephole_optimizations/single_bit_xor.py
  angr/analyses/variable_recovery/engine_ail.py
  tests/test_decompiler.py
Labels: enhancement

#3914 Downgrade unsupported binop log message from an error to a warning
  angr/engines/light/engine.py
Labels: refactor

#3916 Fix partial register reads in RDA.
  angr/analyses/propagator/outdated_definition_walker.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: bug

#3874 Add some new interfaces for propagator; reorganize code
  angr/analyses/__init__.py
  angr/analyses/cfg/__init__.py
  angr/analyses/cfg/cfg_emulated.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_utils.py
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ailblock_walker.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/optimization_passes/const_derefs.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/forward_analysis/forward_analysis.py
  angr/analyses/forward_analysis/job_info.py
  angr/analyses/forward_analysis/visitors/call_graph.py
  angr/analyses/forward_analysis/visitors/function_graph.py
  angr/analyses/forward_analysis/visitors/loop.py
  angr/analyses/init_finder.py
  angr/analyses/loop_analysis.py
  angr/analyses/propagator/call_expr_finder.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/tmpvar_finder.py
  angr/analyses/proximity_graph.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/stack_pointer_tracker.py
  angr/analyses/variable_recovery/variable_recovery.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/analyses/vfg.py
  angr/analyses/xrefs.py
  angr/engines/light/engine.py
  angr/graph_utils.py
  angr/knowledge_plugins/propagations/__init__.py
  angr/knowledge_plugins/propagations/prop_value.py
  angr/knowledge_plugins/propagations/propagation_model.py
  angr/knowledge_plugins/propagations/states.py
  angr/utils/graph.py
  docs/api.rst
Labels: refactor

#3920 Phoenix: Fix the address of ConditionNode in some cases.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3919 AILSimplifier: Fix call expr folding when exprs used in calls are outdated at use sites.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/knowledge_plugins/key_definitions/rd_model.py
  angr/knowledge_plugins/propagations/states.py
Labels: bug

#3921 Fix C address mapping for newlines
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#3922 DivSimplifier: Fix the exponential call in _ail_handle_Add.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
Labels: bug

#3927 Phoenix: Fix missing statements in matching against type D cascading boolean expressions.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#3928 CFG: Fix missing main functions in some binaries when main overlaps with _ftext.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement
