Repository angr/angr, pull requests merged in 2024-09, with the labels that each got.

#4821 CallingConventionAnalysis: Supports tail jumps when collecting call-site effects.
  angr/analyses/calling_convention.py
Labels: enhancement

#4820 Typehoon: Handle join and meet on pointer base types.
  angr/analyses/typehoon/simple_solver.py
Labels: enhancement

#4822 CCA: Improve callsite info collection for PLT stubs.
  angr/analyses/calling_convention.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#4834 Fix an accessor order bug in DuplicationReverter
  angr/analyses/decompiler/optimization_passes/duplication_reverter/duplication_reverter.py
Labels: bug

#4837 Handle zero division in VRA
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_vex.py
Labels: bug

#4842 Remove angr service
  angr/service.py
  setup.cfg
Labels: refactor

#4786 Typehoon: Map typevars to their equivalent replacements. Fix #4758 and #4759.
  angr/analyses/typehoon/simple_solver.py
Labels: bug

#4847 VRA and CondProc: Support CasCmpXX operations.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/variable_recovery/engine_ail.py
Labels: enhancement

#4853 DuplicationReverter: Resilience against clone_graph_replace_splits failures.
  angr/analyses/decompiler/optimization_passes/duplication_reverter/ail_merge_graph.py
  angr/analyses/decompiler/optimization_passes/duplication_reverter/duplication_reverter.py
Labels: enhancement

#4854 CondProc: Handle GetMSBs.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#4852 SimTypes: Introduce int128_t and int256_t.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/sim_type.py
Labels: enhancement

#4858 Enable timing statistics for each simplification pass.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/utils/timing.py
Labels: enhancement

#4860 DuplicationReverter: Do not cache None as the entry block for a graph.
  angr/analyses/decompiler/optimization_passes/duplication_reverter/duplication_reverter.py
Labels: bug

#4862 Typehoon: Fix subtype with None being typevars.
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/variable_recovery/engine_vex.py
Labels: bug

#4863 LightVEXMixin: Fix the vector expr regex.
  angr/engines/light/engine.py
Labels: bug

#4788 SimCCMisrosoftAMD64: Support returning structs
  angr/analyses/variable_recovery/engine_vex.py
  angr/calling_conventions.py
  tests/test_calling_conventions.py
Labels: bug

#4864 SPTracker: Fix infinite loops caused by resilience mode.
  angr/analyses/stack_pointer_tracker.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4866 Clinic: Only leave reachable nodes from function entry in the AIL graph.
  angr/analyses/decompiler/clinic.py
  angr/errors.py
Labels: enhancement

#4868 CFGFast: Ensure irsb_string is always set.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#4869 Propagator: Fix an unset variable issue.
  angr/analyses/propagator/engine_ail.py
Labels: bug

#4872 CFGFast: Attempt to match against pointer arrays during scanning.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#4878 Add a test case for PR #4872 and adjust the logic.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/cfg/memory_data.py
  tests/analyses/cfg/test_cfgfast.py
Labels: enhancement

#4882 SimEngineLightAILMixin: Fix operanad size mismatch in Sar handler.
  angr/engines/light/engine.py
Labels: bug

#4880 RDA: Fix a case where prototype library names is missing in function handler.
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#4881 AILSimplifier: Handle cases where vvar is None in src_and_vvars.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#4865 Add decompilation presets.
  angr/__main__.py
  angr/analyses/decompiler/__init__.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/presets/__init__.py
  angr/analyses/decompiler/presets/basic.py
  angr/analyses/decompiler/presets/fast.py
  angr/analyses/decompiler/presets/full.py
  angr/analyses/decompiler/presets/preset.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
  tests/test_cli.py
Labels: enhancement

#4886 CallSiteMaker: Do not fold Phi variables into call statements.
  angr/analyses/decompiler/callsite_maker.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4888 CFG: Set correct end instruction addresses if a block breaks in the middle of an instruction post normalization.
  angr/analyses/calling_convention.py
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function.py
Labels: bug

#4889 JumptableResolver: Catch claripy BackendError when creating SI.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#4891 SeqnodeDephication: Remove phi statements from LoopNode initializers.
  angr/analyses/decompiler/dephication/seqnode_dephication.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
Labels: bug

#4892 Decompiler: Respect updated entry node address in optimizations.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#4894 RDA.VEXEngine: Implement the Mod handler.
  angr/analyses/reaching_definitions/engine_vex.py
Labels: enhancement

#4895 CFG: Do not generate jobs in unmapped areas.
  angr/analyses/cfg/cfg_base.py
  tests/analyses/cfg/test_cfgfast.py
Labels: enhancement

#4896 CondProc: Add InterleaveLOV and InterleaveHIV.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement
