Repository angr/angr, pull requests merged in 2024-10, with the labels that each got.

#4934 AMD64CCallRewriter: Support CondZ/CondNZ + DEC.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#4935 Fix checking of invalid instructions against the dirty addresses set.
  angr/engines/vex/heavy/heavy.py
  tests/sim/test_self_modifying_code.py
Labels: bug

#4937 dereference_simtype: Handle multiple anonymous structs in the same struct.
  angr/sim_type.py
  tests/test_types.py
Labels: bug

#4940 SimUnion.size: Add a fall back when all members are bottom.
  angr/sim_type.py
  tests/test_types.py
Labels: bug

#4941 PropagatorVEX: Fix zero division errors in the DivMod handler.
  angr/engines/light/engine.py
Labels: bug

#4944 SPropagator: Exclude jump sites when counting vvar uses.
  angr/analyses/s_propagator.py
Labels: bug

#4943 ExprNarrowing: Correct the logic and clean up the implementation.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/expression_narrower.py
Labels: bug

#4945 SequenceWalker: CascadingCondition handler should create new node if necessary.
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/sequence_walker.py
  angr/engines/light/engine.py
Labels: bug

#4946 ITERegionConverter: Use the correct region tail predecessors when fixing phi stmts.
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#4947 SimCCCdecl/SimCCMicrosoftAMD64: next_arg() handles arg_type.size being None.
  angr/calling_conventions.py
Labels: bug

#4949 ExpressionNarrower: Save newly created VVars.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/expression_narrower.py
Labels: bug, enhancement

#4958 ExpressionNarrower: Do not use outdated expressions.
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
Labels: bug, enhancement

#4960 DeadAssignmentRemoval: Properly handle a = Conv(Call) assignments.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#4961 MemoryObject: Handle FP objects.
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
  angr/storage/memory_object.py
Labels: bug

#4967 check_divisor: Handle when divisor is 0.
  angr/analyses/decompiler/optimization_passes/div_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/const_mull_a_shift.py
Labels: bug

#4968 GraphDephicationVVarMapping._insert_vvar_copy: Copy param vvar to reg vvar.
  angr/analyses/decompiler/dephication/graph_vvar_mapping.py
Labels: bug

#4969 simplify_switch_clusters: Fix a potential empty list deref.
  angr/analyses/decompiler/region_simplifiers/switch_cluster_simplifier.py
Labels: bug

#4971 Decompiler: Rewrite remaining tmps to vvars.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/rewriting_state.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/decompiler/ssailification/traversal.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
  angr/analyses/decompiler/ssailification/traversal_state.py
  angr/analyses/s_propagator.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/key_definitions/atoms.py
Labels: bug, enhancement

#4974 fix(mips_elf_fast): Fixed jr to struct members
  angr/analyses/cfg/indirect_jump_resolvers/mips_elf_fast.py
Labels: bug

#4975 SPTracker: Handle bit mask 0xfffffff8.
  angr/utils/constants.py
  tests/analyses/test_stack_pointer_tracker.py
Labels: enhancement

#4976 LoopSimplifier: Do not shove phi nodes into for.iterator.
  angr/analyses/decompiler/region_simplifiers/loop.py
Labels: bug

#4977 ITERegionConverter: Only update the intended phi statements.
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#4978 VRA: Fix the 'variable' unassigned bug.
  angr/analyses/variable_recovery/engine_base.py
Labels: bug

#4981 Decompiler: Handle dirty exprs and VEXCCall exprs properly.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
Labels: enhancement

#4980 CondProc: Add a catch-all ail-to-claripy AST converter.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#4982 Fix the uses of DirtyStatement and DirtyExpression.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/engines/light/engine.py
  tests/analyses/reaching_definitions/test_reachingdefinitions.py
Labels: enhancement

#4984 SSA: Add missing handlers leading to ignoring CallExprs in SSA.
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
Labels: bug

#4985 RI: make_supergraph should not remove entry nodes.
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#4987 SwitchClusterSimplifier: Ensure outermost_node is a ConditionNode.
  angr/analyses/decompiler/region_simplifiers/switch_cluster_simplifier.py
Labels: bug

#4986 SSA: Fix vvar ID duplicates caused by Statement hash collision.
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
Labels: bug

#4988 InlinedString: Support neg.
  angr/analyses/decompiler/optimization_passes/inlined_string_transformation_simplifier.py
Labels: enhancement

#4989 WinStackCanarySimplifier: Test if endpoint_preds is empty before accessing.
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
Labels: bug

#4990 Convert simplification: Only simplify int->int conversions.
  angr/analyses/decompiler/peephole_optimizations/remove_cascading_conversions.py
Labels: bug

#4992 SwitchDefaultCaseDuplicator: Dedup default addrs.
  angr/analyses/decompiler/optimization_passes/switch_default_case_duplicator.py
Labels: bug

#4991 CallsiteMaker: Use stmt instead of insn when finding arg defs.
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/s_reaching_definitions/s_rda_view.py
Labels: bug

#4993 Fix block ID collision between ReturnDuplicatorHigh and ReturnDuplicatorLow.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_high.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_low.py
Labels: bug

#4994 Phoenix: Region head should not be the second node of a loop body.
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4995 ITERegionConverter: Do not force the existence of true_stmt_src.vex_block_addr.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#4996 Dominators: Randomly select an end node on fully cyclic graphs.
  angr/utils/graph.py
Labels: bug

#5002 InlinedStringTransformationSimplifier: Add BitwiseNeg handler.
  angr/analyses/decompiler/optimization_passes/inlined_string_transformation_simplifier.py
Labels: bug

#5003 Clinic._convert_all: Handle NoDecode blocks.
  angr/analyses/decompiler/clinic.py
Labels: bug

#5006 Add PatchFinder.
  angr/analyses/__init__.py
  angr/analyses/patchfinder.py
  angr/utils/bits.py
  tests/analyses/test_patchfinder.py
Labels: enhancement

#5005 Add code-cave analysis.
  angr/analyses/__init__.py
  angr/analyses/codecave.py
  tests/analyses/test_codecaves.py
Labels: enhancement

#5009 Store arch in SimStateHistory.
  angr/state_plugins/history.py
Labels: enhancement

#5007 FunctionManager: Better support for renamed functions.
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
  angr/knowledge_plugins/functions/soot_function.py
  tests/knowledge_plugins/functions/test_function_manager.py
Labels: enhancement

#5010 Decompiler: Reimplement slicing.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/tag_slicer.py
Labels: enhancement

#5008 support multiple knowledge bases for on-the-fly creation and serialization.
  angr/project.py
  tests/serialization/test_pickle.py
Labels: enhancement

#5011 ConstantDereferences: Support derefs in iHex.
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
Labels: enhancement

#5004 Add SelfModifyingCodeAnalysis.
  angr/analyses/__init__.py
  angr/analyses/smc.py
  angr/utils/tagged_interval_map.py
  tests/analyses/test_smc.py
Labels: enhancement

#4679 Pathfinder analysis
  angr/analyses/__init__.py
  angr/analyses/pathfinder.py
  angr/engines/vex/heavy/heavy.py
Labels: enhancement

#5014 SimCC may convert size-mismatching BVVs to func params.
  angr/calling_conventions.py
Labels: enhancement

#5013 CondProc: Do not treat loads of an addr as the same variable.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/return_maker.py
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4846 Some handy binary deobfuscation techniques.
  angr/analyses/__init__.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/deobfuscator/__init__.py
  angr/analyses/deobfuscator/api_obf_finder.py
  angr/analyses/deobfuscator/api_obf_peephole_optimizer.py
  angr/analyses/deobfuscator/irsb_reg_collector.py
  angr/analyses/deobfuscator/string_obf_finder.py
  angr/analyses/deobfuscator/string_obf_opt_passes.py
  angr/analyses/deobfuscator/string_obf_peephole_optimizer.py
  angr/analyses/unpacker/__init__.py
  angr/analyses/unpacker/obfuscation_detector.py
  angr/analyses/unpacker/packing_detector.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/obfuscations.py
  tests/analyses/test_api_obf_finder.py
  tests/analyses/test_deobfuscation.py
  tests/analyses/test_string_obf_finder.py
  tests/analyses/test_unpacking.py
Labels: enhancement

#5016 CondProc: Explicitly encodes ins_addr in Loads.
  angr/analyses/decompiler/condition_processor.py
Labels: bug, enhancement

#5017 Add _op_fgeneric_RSqrtEst.
  angr/engines/vex/claripy/irop.py
Labels: enhancement

#5019 SPropagator: Propagate global variable to uses more aggressively.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/dephication/graph_vvar_mapping.py
  angr/analyses/decompiler/ssailification/traversal.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
  angr/analyses/s_liveness.py
  angr/analyses/s_propagator.py
  angr/calling_conventions.py
  angr/utils/ssa/__init__.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement
