Repository angr/angr, pull requests merged in 2024-07, with the labels that each got.

#4705 CondProc: Be resilient against condition.idx being None.
  angr/analyses/decompiler/condition_processor.py
Labels: enhancement

#4610 SimType & friends: Fully typecheck, fix observed bugs
  angr/analyses/decompiler/structured_codegen/c.py
  angr/calling_conventions.py
  angr/procedures/stubs/ReturnUnconstrained.py
  angr/procedures/stubs/syscall_stub.py
  angr/sim_type.py
  angr/state_plugins/debug_variables.py
  tests/knowledge_plugins/functions/test_function2.py
  tests/test_types.py
Labels: refactor

#4719 DeadblockRemover: Do not simplify conditions when recovering reaching conditions to speed things up.
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/optimization_passes/deadblock_remover.py
Labels: enhancement

#4721 AngrDb: Store and use load args for cle backends.
  angr/analyses/cfg/cfg_base.py
  angr/angrdb/serializers/loader.py
  tests/serialization/test_db.py
Labels: enhancement

#4722 Multiple fixes involving RedundantLabelRemover, Phoenix cyclic refinement, and ReturnDuplicator.
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_low.py
  angr/analyses/decompiler/redundant_label_remover.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug
