Repository angr/angr, pull requests merged in 2024-11, with the labels that each got.

#5021 add test for decompiler resilience and error loading
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/structured_codegen/dwarf_import.py
  angr/angrdb/models.py
  angr/angrdb/serializers/kb.py
  angr/angrdb/serializers/structured_code.py
  angr/knowledge_base.py
  angr/knowledge_plugins/__init__.py
  angr/knowledge_plugins/decompilation.py
  angr/knowledge_plugins/structured_code.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/decompiler/test_errors.py
Labels: tests

#5022 Incorrect arg order for strncpy
  angr/analyses/reaching_definitions/function_handler_library/string.py
Labels: bug

#5023 CFG: Support Win32 hot-patch points.
  angr/analyses/cfg/cfg_fast.py
  tests/analyses/cfg/test_cfgfast.py
Labels: bug

#5031 Decompiler: Propagate fail-fast setting to subanalyses.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
Labels: enhancement

#5032 Structuring: Properly handle entries reused in switch-cases.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/label_collector.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/switch_default_case_duplicator.py
  angr/analyses/decompiler/optimization_passes/switch_reused_entry_rewriter.py
  angr/analyses/decompiler/presets/basic.py
  angr/analyses/decompiler/presets/fast.py
  angr/analyses/decompiler/presets/full.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5041 VRA: VEXEngine should clear return regs after calls.
  angr/analyses/variable_recovery/engine_vex.py
  tests/analyses/test_calling_convention_analysis.py
Labels: bug

#5042 SimEngineLightAILMixin: Fix the logic of _ail_handle_Mull.
  angr/engines/light/engine.py
Labels: bug

#5044 RegionIdentifier: Update entry_node during make_supergraph.
  angr/analyses/decompiler/region_identifier.py
  tests/analyses/test_regionidentifier.py
Labels: bug

#5045 Phoenix: Handle cases where multiple last statements are removed.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/utils.py
Labels: bug

#5046 Decompiler: Properly rewrite and handle Store.guard expressions.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
Labels: bug

#5028 Add Decompiler Corpus Test Framework
  .github/workflows/corpus_test-nightly.yml
  .github/workflows/corpus_test.yml
  corpus_tests/README.md
  corpus_tests/conftest.py
  corpus_tests/scripts/classify_diff.sh
  corpus_tests/scripts/gh_create_branch.sh
  corpus_tests/scripts/gh_ls.sh
  corpus_tests/scripts/gh_push_file.sh
  corpus_tests/scripts/snapshot_diff.sh
  corpus_tests/test_corpus.py
Labels: enhancement

#5052 Multiple fixes for corpus tests.
  .github/workflows/corpus_test.yml
  corpus_tests/scripts/snapshot_diff.sh
Labels: bug
