Repository angr/angr, pull requests merged in 2024-01, with the labels that each got.

#4403 Rewrite dfs_back_edges to be iterative
  angr/utils/graph.py
Labels: enhancement

#4408 Multiple decompiler and pcode fixes. Also add a new SimOS for cummins_nxp.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
  angr/analyses/reaching_definitions/rd_initializer.py
  angr/analyses/reaching_definitions/rd_state.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/engines/pcode/cc.py
  angr/knowledge_plugins/propagations/states.py
  angr/project.py
  angr/simos/__init__.py
  angr/simos/simos.py
  angr/simos/snimmuc_nxp.py
  setup.cfg
Labels: bug, enhancement

#4409 CFG: Do not re-add function addresses to completed_functions.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#4427 CCA: Fix a crash when the register name is not in arch.registers.
  angr/calling_conventions.py
Labels: bug

#4428 Push return value for fake ret
  angr/engines/vex/heavy/heavy.py
Labels: bug

#4414 Fix bug for DFS when getting dominators
  angr/utils/graph.py
  tests/utils/__init__.py
  tests/utils/test_graph.py
Labels: bug

#4434 complement erroneously written as compliment
  docs/core-concepts/solver.rst
Labels: bug
