Repository angr/angr, pull requests merged in 2024-03, with the labels that each got.

#4485 Add a SwitchDefaultCaseDuplicator optimization pass.
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/switch_default_case_duplicator.py
Labels: enhancement

#4483 JumptableResolver: Support secondary indirection.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/analyses/cfg/test_jumptables.py
Labels: enhancement

#4484 Typehoon: Reduce duplicate constraint graph generation effort.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typeconsts.py
Labels: enhancement

#4487 RDA: Fix missing tmp uses when track_tmps is True.
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/knowledge_plugins/propagations/states.py
Labels: bug

#4490 PeepholeOptimization: Support bswap32.
  angr/analyses/decompiler/peephole_optimizations/bswap.py
Labels: enhancement

#4489 Propagator & RDA: Support AddV and MulV in AIL.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: enhancement

#4491 Decompiler: Handle simple alloca()s.
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/stack_pointer_tracker.py
Labels: enhancement

#4493 Typehoon: Solve a typevar as primitive if it can't be made a struct.
  angr/analyses/typehoon/simple_solver.py
Labels: bug

#4498 Decompiler: Support reflowing types of function arguments.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug, enhancement

#4499 CFG: Support section-less segments on ELFs with sections.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#4502 Fix a propagation bug that does not check defenitions
  angr/analyses/decompiler/ail_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4503 Add cross instruction optimization as an option to StackPointerTracker
  angr/analyses/decompiler/clinic.py
  angr/analyses/stack_pointer_tracker.py
Labels: bug

#4517 CFG & JumptableResolver: Fix issue #3768.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#4522 Set Endness for MemoryLocation Atom In atom.from_argument
  angr/knowledge_plugins/key_definitions/atoms.py
Labels: bug

#4527 VRA: Remove variables that are created first for top addrs.
  angr/analyses/decompiler/clinic.py
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4507 Do not perform narrow_exprs() on floating point and double precision floats
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: enhancement

#4528 ConstantResolver: Do not crash if the function does not exist.
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
Labels: bug

#4529 CFGFast: Resilience against CFGJob without src_node. Close #4526.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#4535 Support ExpCmpNE and Clz in Propagator and RDA.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/propagator/engine_ail.py
  angr/analyses/reaching_definitions/engine_ail.py
Labels: enhancement

#4536 RegionIdentifier: Fix issues in making incomplete switch-case nodes.
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
Labels: bug, enhancement

#4532 Have TypeError in Disassembly provide more informative error message.
  angr/analyses/disassembly.py
  tests/analyses/test_disassembly.py
Labels: enhancement

#4537 CondProc: ExpCmpNE should be a BoolS.
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#4538 RegionIdentifier: Add edges between region successors.
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/reaching_definitions/engine_ail.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#4539 Fix support for decompiling all functions in CLI.
  angr/analyses/decompiler/utils.py
Labels: bug

#4542 AILSimplifier: Do not generate zero-bit registers out of narrow_exprs.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/condition_processor.py
Labels: bug

#4541 Decompiler: Handle DivMod with operand size conversions.
  angr/analyses/propagator/engine_ail.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/engines/light/engine.py
Labels: bug

#4543 Fix multi-MO merge in MVListPage. Fix fixed-point detection in Propagator and RDA.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/find_objects_static.py
  angr/analyses/propagator/propagator.py
  angr/analyses/reaching_definitions/reaching_definitions.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/knowledge_plugins/key_definitions/live_definitions.py
  angr/knowledge_plugins/propagations/states.py
  angr/storage/memory_mixins/multi_value_merger_mixin.py
  angr/storage/memory_mixins/paged_memory/pages/mv_list_page.py
  tests/analyses/reaching_definitions/results/x86_64/all_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/fauxware_definitions.pickle
  tests/analyses/reaching_definitions/results/x86_64/loop_definitions.pickle
Labels: bug

#4551 AILSimplifier: Fix an incorrect reg unification case.
  angr/analyses/decompiler/ail_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug
