Repository angr/angr, pull requests merged in 2025-06, with the labels that each got.

#5515 Decompiler: Keep clinic graphs intact post decompilation.
  angr/analyses/decompiler/decompiler.py
Labels: enhancement

#5513 Type inference speed improvements: Strike 2.
  angr/analyses/decompiler/clinic.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/variable_recovery/engine_ail.py
Labels: enhancement

#5514 VRA: Use function graph for dominance frontier if available.
  angr/analyses/decompiler/clinic.py
  angr/analyses/variable_recovery/variable_recovery_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/utils/graph.py
Labels: enhancement

#5522 Fix store and extract for SimTypeWideChar.
  angr/sim_type.py
  tests/types/test_simtypefunction.py
  tests/types/test_types.py
Labels: bug

#5523 BlockSimplifier: Fix incorrect removal of call statements.
  angr/analyses/decompiler/block_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5524 Project: Query kernel32.dll for APIs in api-ms-win-xxx.dll.
  angr/project.py
Labels: enhancement

#5525 Improve handling of phi var-involving constant propagation.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
  angr/analyses/s_reaching_definitions/s_reaching_definitions.py
  angr/utils/ssa/__init__.py
Labels: enhancement

#5526 VRA: Limit stack variable stores to 256 bytes.
  angr/analyses/variable_recovery/engine_base.py
Labels: enhancement

#5530 Peephole: Signed division simplification case B.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_div_const_mul_const.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  angr/analyses/decompiler/peephole_optimizations/modulo_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/optimized_div_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_bitmasks.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5532 SPropagator: Propagate stackvars that are not eliminatable.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/s_propagator.py
  angr/utils/ssa/__init__.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5543 SAILR: Fix indentation (and the heuristics).
  angr/analyses/decompiler/counters/call_counter.py
  angr/analyses/decompiler/region_simplifiers/goto.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/sailr.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5544 GraphRegion: Use new sub graph regions when replacing subgraphs.
  angr/analyses/decompiler/graph_region.py
Labels: bug

#5539 Fix the implementation of to_acyclic_graph.
  angr/utils/graph.py
Labels: bug

#5547 SAILR: Limit graph and edge scale for heuristic 2.
  angr/analyses/decompiler/structuring/sailr.py
Labels: enhancement

#5548 Phoenix: Speed up acyclic graph conversion.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/utils/graph.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5549 ReturnDuplicatorLow: Set a lower max_func_blocks limit.
  angr/analyses/decompiler/optimization_passes/return_duplicator_low.py
Labels: enhancement

#5550 Merging sub-function definitions into parent all_definitions
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#5554 Decompilation: Fix new bogus variables during subsequent decompilations.
  angr/analyses/variable_recovery/engine_base.py
  tests/gui/test_decompilation_workflows.py
Labels: bug

#5557 FCP: Check if node is in graph before getting its successors.
  angr/analyses/fcp/fcp.py
Labels: bug

#5558 test_decompiling_abnormal_switch_case_case3: Print the actual base type upon failure.
  tests/analyses/decompiler/test_decompiler.py
Labels: refactor

#5538 FLIRT: Catch decompression errors; end when function name bytes >= 0x80.
  angr/analyses/flirt/flirt_sig.py
Labels: enhancement
