Repository angr/angr, pull requests merged in 2025-09, with the labels that each got.

#5644 fix: Pass max_iterations to sub_rda, otherwise it uses default of 30
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#5646 CFGFast: Detect XFG hashes during complete scans.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/analyses/decompiler/test_peephole_wstrcpy.py
Labels: enhancement

#5657 CFGFast: Enable function hints for PEs.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_fast.py
  tests/analyses/decompiler/test_structurer.py
Labels: enhancement

#5665 Check that jump_source is not None
  angr/simos/windows.py
Labels: bug

#5664 SimpleSolver: Fix a zero division caused by unknown struct types.
  angr/analyses/typehoon/simple_solver.py
Labels: bug

#5667 Phoenix: _refine_cyclic_core handle missing fallthrough nodes.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#5668 ITERegionConveter: Fix a bug caused by variable name conflict.
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#5670 SwitchCaseNode can have both in- and out-region successors.
  angr/analyses/decompiler/structuring/phoenix.py
Labels: bug

#5671 SPTracker: Check if sp_v is None before subtracting. Add a new alignment mask.
  angr/analyses/stack_pointer_tracker.py
  angr/utils/constants.py
Labels: bug, enhancement

#5672 Function.holes(): Count holes in its linear control flow.
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#5673 Typehoon: Consider out edges of all nodes in an equiv class.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/lifter.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/test_typehoon.py
Labels: bug

#5674 Typehoon: Solution cache considers equivalence classes.
  .pre-commit-config.yaml
  angr/analyses/typehoon/simple_solver.py
  tests/analyses/test_typehoon.py
Labels: enhancement

#5686 FlirtAnalysis: add a dry-run mode.
  angr/analyses/flirt/flirt.py
Labels: enhancement

#5685 CASRewriting: Add more CAS-related intrinsics.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/cas_intrinsics.py
  angr/analyses/variable_recovery/engine_ail.py
  tests/analyses/decompiler/test_cas_rewriting.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/decompiler/test_head_controlled_loops.py
Labels: enhancement

#5691 Fix non-returning determination from lib protos.
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/parse_win32json.py
  angr/procedures/definitions/wdk/ntoskrnl.json
Labels: bug

#5692 WcscpyConsolidation: Consolidates unordered consecutive calls.
  angr/analyses/decompiler/peephole_optimizations/inlined_wcscpy_consolidation.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_peephole_wcscpy.py
Labels: enhancement
