Repository angr/angr, pull requests merged in 2025-04, with the labels that each got.

#5389 Support demangling Rust symbols and fix a bug in CallingConventionAnalaysis
  angr/analyses/calling_convention/calling_convention.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/knowledge_plugins/functions/function.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5401 Typehoon: Fix non-determinism caused by multiple same-typed members in a struct.
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typehoon.py
  tests/analyses/test_typehoon.py
Labels: bug

#5415 Typehoon: Catch an exception caused by unknown field sizes.
  angr/analyses/typehoon/typehoon.py
Labels: bug

#5418 SPTracker: Set rax to 0 after _alloca_probe.
  angr/analyses/stack_pointer_tracker.py
Labels: bug

#5420 Clinic: Fix remaining ret-addr on the stack after removing chkstk().
  angr/analyses/decompiler/clinic.py
Labels: bug

#5419 CCA: Catch a lifting failure in generate_callsite_subgraph.
  angr/analyses/calling_convention/calling_convention.py
Labels: bug

#5426 CCallRewriterAMD64: Add CondNS.
  angr/analyses/decompiler/ccall_rewriters/amd64_ccalls.py
Labels: enhancement

#5425 CondConstProp: Fix a constant over-propagation.
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
Labels: bug

#5424 GraphUtils: Fix a redundant list iteration in quasi-topological node sorting.
  angr/utils/graph.py
Labels: bug, refactor

#5431 Clinic: Rewrite calls to guard_dispatch_icall.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5436 RegionIdentifier: Sort nodes once and update the order with new regions.
  angr/analyses/decompiler/region_identifier.py
Labels: enhancement

#5440 Typehoon: Recursively solve type constraints.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typehoon.py
Labels: enhancement

#5441 CFGFast._function_completed: Ensure capstone.insns is not empty before accessing.
  angr/analyses/cfg/cfg_fast.py
Labels: bug

#5442 TestMemcmpDefiniteSize: Fix a binary path.
  tests/regression/test_regression_memcmp_definite_size.py
Labels: bug

#5443 CFGFast: Add a missing membership check in common function renaming.
  angr/analyses/cfg/cfg_fast.py
Labels: bug
