Repository angr/angr, pull requests merged in 2025-02, with the labels that each got.

#5232 CFGFast: Add support for __alloca_probe.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/forward_analysis/forward_analysis.py
  angr/analyses/stack_pointer_tracker.py
Labels: enhancement

#5235 Typehoon: Avoid struct fields with negative offsets.
  angr/analyses/typehoon/simple_solver.py
Labels: enhancement

#5233 CFG: Fix jump table addrs during normalization.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  angr/analyses/decompiler/utils.py
Labels: bug

#5234 CCA: Deprioritize fp types in ret type guessing.
  angr/analyses/calling_convention/calling_convention.py
Labels: enhancement

#5236 ReturnDuplicatorBase: Only set graph_changed to True when touching the graph.
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
Labels: bug

#5238 Phoenix: Support switch-case no-default; Default node must be structured before structuring switch-case.
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/utils.py
Labels: bug, enhancement

#5237 Clinic: Handle abnormal switch-case case 2 soundly.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5239 Typehoon: Gracefully handle overlapping struct field accesses.
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/variable_recovery/engine_base.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5240 APIObfuscationFinder: Fix a bad assertion.
  angr/analyses/deobfuscator/api_obf_finder.py
Labels: bug

#5241 MultiValues: Handle FP/BV mixtures.
  angr/storage/memory_mixins/paged_memory/pages/multi_values.py
Labels: bug

#5244 StringObfFinder: Fix argument sizes; Limit callable steps.
  angr/analyses/deobfuscator/string_obf_finder.py
  angr/callable.py
  angr/factory.py
Labels: bug, enhancement

#5245 AILSimplifier: Support narrowing add/sub exprs.
  angr/analyses/decompiler/ail_simplifier.py
Labels: enhancement

#5249 SSA: Handles overlapping stackvars better.
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/s_reaching_definitions/s_rda_view.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5251 Decompiler: Fix missing variables in phi source vvars.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
  angr/analyses/variable_recovery/engine_ail.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5255 VariableManager: Fix missing structs in types when structs are used by multi-level pointers.
  angr/analyses/decompiler/structured_codegen/c.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/utils/types.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5256 OneUseExprFolder: Consider var uses in phi variables.
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5252 LoweredSwitchSimplifier: Limit to vvars; Be more resilient against unordered variable comparisons.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5257 Factory.callable: Take function as the first argument.
  angr/factory.py
  tests/factory/test_callable.py
Labels: enhancement

#5260 Fix a case of flipping nodes with multi preds
  angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5258 CCA: Call-site result should not overwrite func result.
  angr/analyses/calling_convention/calling_convention.py
  angr/analyses/calling_convention/fact_collector.py
  angr/analyses/calling_convention/utils.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/calling_conventions.py
  angr/simos/simos.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5261 RetDup: Duplicate an entire region at once when allowed.
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5263 LoweredSwitchSimplifier: Ensure default node is not reachable from case nodes within the region.
  angr/analyses/decompiler/optimization_passes/duplication_reverter/duplication_reverter.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/region_identifier.py
Labels: bug

#5266 OptimizationPass: Run block simplifiers when simplifying graphs.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
Labels: enhancement

#5267 RetDup: Fix conflict uses of last stmts in copied region heads.
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
Labels: bug

#5264 EagerEval: Handle Const ^ Const.
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
Labels: enhancement

#5270 Dephication: Fix phi-copy insertion.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/dephication/graph_vvar_mapping.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5273 JumpTableResolver: Handle cases where func.startpoint is None.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#5272 Decompiler: Fix type reflowing.
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompiler.py
  angr/utils/library.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5274 Decompiler: Fix decompilation of rep stosX.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/s_liveness.py
  angr/utils/ail.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5279 RegisterSaveAreaSimplifier: Recognize xmm register spills.
  angr/analyses/decompiler/optimization_passes/register_save_area_simplifier.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5280 Demangler: Switch to pydemumble.
  angr/analyses/class_identifier.py
  angr/analyses/find_objects_static.py
  angr/knowledge_plugins/functions/function.py
  angr/procedures/definitions/__init__.py
  angr/utils/cpp.py
  setup.cfg
Labels: enhancement

#5281 Clinic: Update condjumps to jumps if both targets are the same after jump-block removal.
  angr/analyses/decompiler/clinic.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5284 SimOS: irelative_resolver should not return a BVS.
  angr/simos/simos.py
Labels: bug

#5271 Clinic: Guess the sizes of stack-based arrays.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/register_save_area_simplifier.py
  angr/analyses/decompiler/optimization_passes/stack_canary_simplifier.py
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
  angr/analyses/decompiler/stack_item.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/typehoon/simple_solver.py
  angr/analyses/typehoon/typehoon.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/utils/types.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5285 AILSimplifier: Iteratively remove dead vvars.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5192 RegionIdentifier: Update dominators after creating regions.
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/region_identifier.py
  angr/utils/doms.py
  tests/analyses/decompiler/test_decompiler.py
  tests/utils/test_doms.py
Labels: enhancement

#5287 CondConstProp: Avoid graph slicing to speed it up.
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
Labels: enhancement

#5291 Phoenix: Fix an infinite loop when extracting switch exprs.
  angr/analyses/decompiler/utils.py
Labels: bug

#5292 CondConstProp: Deconflict and deduplicate conditions before propagation.
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5294 Faster SRDA and SPropagator.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
  angr/analyses/s_propagator.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
  angr/analyses/s_reaching_definitions/s_rda_view.py
  angr/analyses/s_reaching_definitions/s_reaching_definitions.py
  angr/utils/ssa/__init__.py
  angr/utils/ssa/vvar_uses_collector.py
Labels: enhancement, refactor

#5295 IncrementalDominators: Faster dominance frontier computation.
  angr/utils/doms.py
Labels: enhancement

#5296 CCA: Fix missing prototype_libname for PLT stubs.
  angr/analyses/calling_convention/calling_convention.py
Labels: bug

#5297 ITERegionConverter: Ensure all phi statements in tail region are valid.
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
Labels: bug

#5298 CondConstProp: Never replace Assignment.dst with constants.
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
Labels: bug

#5299 SPropagator: Add a missing is-assignment check.
  angr/analyses/s_propagator.py
Labels: bug

#5300 SRDAView: Ensure a vvar is a stackvar before accessing .stack_offset.
  angr/analyses/s_reaching_definitions/s_rda_view.py
Labels: bug

#5301 SimplifyPCRelativeLoads: Ensure op0.addr is a const.
  angr/analyses/decompiler/peephole_optimizations/simplify_pc_relative_loads.py
Labels: bug

#5304 SPropagator: Do not propagate tmps across blocks.
  angr/analyses/s_propagator.py
  angr/utils/ssa/__init__.py
Labels: bug

#5305 FactCollector: Dereference func prototypes before using .returnty.
  angr/analyses/calling_convention/fact_collector.py
Labels: bug

#5306 VRA: Allow funcaddr_typevar to be None.
  angr/analyses/variable_recovery/engine_ail.py
Labels: bug

#5307 AILSimplifier: Fix infinite loop in _get_vvar_use_and_exprs_recursive.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#5309 CCCA: Implement a fast path when only runs on a few functions.
  angr/analyses/complete_calling_conventions.py
Labels: enhancement

#5308 SRDAModel: Make get_uses_by_location(exprs=True) faster.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
Labels: enhancement

#5310 SimplifyPCRelLoad: Expr.ins_addr is optional.
  angr/analyses/decompiler/peephole_optimizations/simplify_pc_relative_loads.py
Labels: bug

#5311 SimCC: Set RETURN_VAL to None.
  angr/calling_conventions.py
Labels: bug

#5312 VRA: Fix another case where funcaddr_typevar can be None.
  angr/analyses/variable_recovery/engine_ail.py
Labels: bug

#5313 JumpTableResolver: Resilience against unsolvable jump_base_addr.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
Labels: bug

#5314 ConstantResolver: Limit function size for better performance.
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
Labels: enhancement

#5315 AILSimplifier: Fix a potential infinite loop in _get_super_node_blocks.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#5316 Delay import pyformlang to decrease angr import time.
  angr/analyses/typehoon/dfa.py
Labels: refactor

#5318 Decompiler: New peephole opt ASubAShrConstShrConst.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/a_sub_a_shr_const_shr_const.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5317 CCA: Handle non-consecutive stack args.
  angr/analyses/calling_convention/calling_convention.py
  angr/analyses/calling_convention/fact_collector.py
  tests/analyses/test_calling_convention_analysis.py
Labels: enhancement

#5319 VRA: Improve the support of stack-based struct type inference.
  angr/analyses/decompiler/clinic.py
  angr/analyses/typehoon/typehoon.py
  angr/analyses/typehoon/typevars.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5320 BpSaveSimplifier: Enable for all platforms.
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5321 Decompiler: Link struct member info for Loads and vvar reads.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
  angr/analyses/decompiler/structured_codegen/c.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5323 CFGBase: Pass traversed_cfg_nodes to the 2nd _graph_bfs_custom.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#5326 CFGEmulated: Fix #2459 and #5325.
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#5324 CFGFast: Speed up job popping and reduce job sorting attempts.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#5329 Minor refactors to speed up decompiling large functions.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
Labels: refactor
