Repository angr/angr, pull requests merged in 2025-03, with the labels that each got.

#5341 CFGFast: Identify _alloca_probe for X86 PEs.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#5342 WinStackCanarySimplifier: Support x86 PEs.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
  angr/utils/funcid.py
Labels: enhancement

#5343 SPTracker: Fix handling of alloca_probe and chkstk; fix callee-cleanup sp adjustment.
  angr/analyses/stack_pointer_tracker.py
Labels: bug

#5344 Clinic: Remove chkstk and alloca_probe calls.
  angr/analyses/decompiler/clinic.py
Labels: enhancement

#5350 fix AttributeError when decompilation fails
  angr/knowledge_plugins/functions/function.py
Labels: bug

#5354 Flirt: Migrate from nampa to a self-contained implementation.
  angr/analyses/flirt/__init__.py
  angr/analyses/flirt/consts.py
  angr/analyses/flirt/flirt.py
  angr/analyses/flirt/flirt_function.py
  angr/analyses/flirt/flirt_matcher.py
  angr/analyses/flirt/flirt_module.py
  angr/analyses/flirt/flirt_node.py
  angr/analyses/flirt/flirt_sig.py
  angr/analyses/flirt/flirt_utils.py
  angr/flirt/__init__.py
  angr/knowledge_plugins/functions/function.py
  pyproject.toml
Labels: enhancement, refactor

#5356 Avoid re-lifting when accessing Function.size.
  angr/knowledge_plugins/functions/function.py
Labels: refactor

#5357 Block.instructions: Avoid transferring stmts from VEX.
  angr/block.py
Labels: enhancement

#5358 CFG: Fix no-op-block logic in mark_function_alignments.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#5359 add implementation for 32-bit floating point sqrt concretizer
  angr/engines/vex/heavy/concretizers.py
Labels: enhancement

#5361 CFG: Extend tail-call detection to all functions.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#5363 SPTracker: Support THUMB-mode accesses to itstate and related tmps.
  angr/analyses/stack_pointer_tracker.py
  tests/analyses/cfg/test_jumptables.py
Labels: bug

#5368 Decompiler: Fix long multi-statement expressions.
  angr/analyses/decompiler/counters/call_counter.py
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_conversions.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5331 Decompiler: Better support of C++ function calls
  angr/analyses/calling_convention/calling_convention.py
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/base_ptr_save_simplifier.py
  angr/analyses/decompiler/optimization_passes/determine_load_sizes.py
  angr/analyses/decompiler/optimization_passes/eager_std_string_concatenation.py
  angr/analyses/decompiler/optimization_passes/engine_base.py
  angr/analyses/decompiler/optimization_passes/inlined_string_transformation_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/win_stack_canary_simplifier.py
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/base.py
  angr/analyses/decompiler/peephole_optimizations/constant_derefs.py
  angr/analyses/decompiler/peephole_optimizations/inlined_strcpy.py
  angr/analyses/decompiler/peephole_optimizations/inlined_strcpy_consolidation.py
  angr/analyses/decompiler/peephole_optimizations/remove_cxx_destructor_calls.py
  angr/analyses/decompiler/peephole_optimizations/rewrite_cxx_operator_calls.py
  angr/analyses/decompiler/presets/fast.py
  angr/analyses/decompiler/presets/full.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/decompiler/ssailification/traversal_engine.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/decompiler/utils.py
  angr/analyses/typehoon/lifter.py
  angr/analyses/typehoon/translator.py
  angr/analyses/typehoon/typeconsts.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/calling_conventions.py
  angr/engines/light/engine.py
  angr/knowledge_plugins/propagations/states.py
  angr/knowledge_plugins/variables/variable_manager.py
  angr/procedures/definitions/__init__.py
  angr/procedures/definitions/types_stl.py
  angr/sim_type.py
  pyproject.toml
  tests/analyses/decompiler/test_decompiler.py
  tests/test_types.py
Labels: enhancement

#5375 VRA: Check existing vars before creating new ones in read_reg.
  angr/analyses/variable_recovery/engine_base.py
  angr/knowledge_plugins/variables/variable_manager.py
Labels: bug

#5378 SimTypes: Fix parsing issues for C++ ctors and dtors.
  angr/sim_type.py
  tests/test_types.py
Labels: bug

#5379 Fix: SimTypeCppFunction misses _with_arch method.
  angr/sim_type.py
Labels: bug

#5380 SRDAView: Fix missing update to predicate_returned_true.
  angr/analyses/s_reaching_definitions/s_rda_view.py
Labels: bug

#5381 Clinic: Loosen max type constraint limit.
  angr/analyses/decompiler/clinic.py
Labels: enhancement

#5376 Update LICENSE and COPYRIGHT.
  COPYRIGHT
  LICENSE
Labels: refactor

#5382 CFGFast: Fix the re-detection bug in bp_as_gpr detection.
  angr/analyses/cfg/cfg_fast.py
  tests/analyses/test_calling_convention_analysis.py
Labels: bug

#5383 CCA: Fix callsite stack arg analysis by considering STACKARG_SP_DIFF.
  angr/analyses/calling_convention/calling_convention.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/test_calling_convention_analysis.py
Labels: bug

#5385 StructuredCodeGen: Fix the redundant comma in C++-like method calls.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug
