Repository angr/angr, pull requests merged in 2025-07, with the labels that each got.

#5568 fix: Some inconsitencies with RDA function handlers
  angr/analyses/reaching_definitions/function_handler.py
  angr/analyses/reaching_definitions/function_handler_library/stdio.py
  angr/analyses/reaching_definitions/function_handler_library/stdlib.py
  angr/analyses/reaching_definitions/function_handler_library/string.py
  angr/analyses/reaching_definitions/function_handler_library/unistd.py
Labels: bug

#5570 CFGBase: Lift fewer blocks when finding bad function starts.
  angr/analyses/cfg/cfg_base.py
Labels: enhancement

#5571 ConstResolver: More caching and filtering for fewer FCP calls.
  angr/analyses/cfg/indirect_jump_resolvers/arm_elf_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
  angr/blade.py
  angr/knowledge_plugins/propagations/propagation_model.py
  angr/utils/vex.py
Labels: enhancement

#5574 Three fixes in region identifier and phoenix for bizarre switch-cases.
  angr/analyses/decompiler/optimization_passes/deadblock_remover.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
  angr/analyses/decompiler/utils.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5575 Struct.size: Do not raise exceptions if the last field is a BOT.
  angr/analyses/typehoon/typeconsts.py
Labels: bug

#5577 to_acyclic_graph: Fix an off-by-one error when removing edges.
  angr/utils/graph.py
Labels: bug

#5579 GraphRegion: Fix an issue causing duplicated GraphRegions.
  angr/analyses/decompiler/graph_region.py
  angr/analyses/decompiler/structuring/recursive_structurer.py
  tests/analyses/decompiler/test_structurer.py
Labels: bug

#5580 Fix missing type check in _find_node_in_graph.
  angr/analyses/decompiler/utils.py
Labels: bug

#5581 Phoenix: Do not make a switch if node_a is region head.
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_structurer.py
Labels: bug

#5584 CallsiteMaker: Expand struct arg locs recursively.
  angr/analyses/decompiler/callsite_maker.py
Labels: bug

#5585 Phoenix: Fix natural loop creation logic in subgraphs.
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_structurer.py
Labels: bug

#5586 CFGEmulated: Catch AngrSyscallError when getting syscall procedures.
  angr/analyses/cfg/cfg_emulated.py
Labels: bug

#5587 AILSimplifier: Fix stmt ID mismatches in calls/assignments_to_remove.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#5588 CFGFast: Reduce segment list fragmentation for ARMCortexM binaries.
  angr/analyses/cfg/cfg_fast.py
  tests/utils/test_segment_list.py
Labels: bug, enhancement

#5535 Peephole: Add inlined memcpy recognition.
  angr/analyses/decompiler/peephole_optimizations/__init__.py
  angr/analyses/decompiler/peephole_optimizations/inlined_memcpy.py
Labels: enhancement

#5533 Enhance Type 3 string obfuscation finder.
  angr/analyses/deobfuscator/string_obf_finder.py
Labels: enhancement

#5598 Phoenix: Fix bad fullgraphs after cyclic refinement.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/node_replacer.py
  angr/analyses/decompiler/optimization_passes/lowered_switch_simplifier.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_low.py
  angr/analyses/decompiler/region_identifier.py
  angr/analyses/decompiler/sequence_walker.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/utils.py
  angr/utils/graph.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5601 RDA: Fix regression with multiple addresses in load
  angr/analyses/reaching_definitions/engine_vex.py
  tests/analyses/reaching_definitions/test_regressions.py
Labels: bug

#5609 Add decompilation notes support.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompilation_cache.py
  angr/analyses/decompiler/decompilation_options.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/notes/__init__.py
  angr/analyses/decompiler/notes/decompilation_note.py
  angr/analyses/decompiler/notes/deobfuscated_strings.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/structured_codegen/base.py
  angr/analyses/decompiler/structured_codegen/c.py
  angr/analyses/deobfuscator/string_obf_finder.py
  angr/analyses/deobfuscator/string_obf_opt_passes.py
  tests/analyses/decompiler/test_decompilation_notes.py
  tests/analyses/test_string_obf_finder.py
Labels: enhancement

#5612 CFB: Prioritize segments for ELFs.
  angr/analyses/cfg/cfb.py
Labels: enhancement
