Repository angr/angr, pull requests merged in 2025-01, with the labels that each got.

#5119 Aggressively add jumpkinds to the protobuf enum
  angr/protos/__init__.py
  angr/protos/cfg_pb2.py
  angr/protos/function_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  angr/protos/variables_pb2.py
  angr/protos/xrefs_pb2.py
  angr/utils/enums_conv.py
Labels: bug

#5120 Propagator: Remove AIL support and unnecessary code.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/propagator/engine_base.py
  angr/analyses/propagator/outdated_definition_walker.py
  angr/analyses/propagator/propagator.py
  angr/analyses/propagator/tmpvar_finder.py
  angr/analyses/s_propagator.py
  angr/knowledge_plugins/propagations/propagation_model.py
  angr/knowledge_plugins/propagations/states.py
Labels: refactor

#5121 timing: Add print_timing_total. Allow setting TD using envvar.
  angr/utils/timing.py
Labels: enhancement

#5122 CFG: Enable PE IAT resolver for XBE.
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
  angr/analyses/cfg/indirect_jump_resolvers/x86_pe_iat.py
Labels: enhancement

#5123 FactCollector: Do not alter function prototype.
  angr/analyses/calling_convention/fact_collector.py
Labels: bug

#5124 Fast constant propagation for VEX
  angr/analyses/__init__.py
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  angr/analyses/cfg/indirect_jump_resolvers/propagator_utils.py
  angr/analyses/fcp/__init__.py
  angr/analyses/fcp/fcp.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/test_fcp.py
Labels: enhancement

#5125 Add SimXbox and hook Xbox kernel APIs.
  angr/simos/__init__.py
  angr/simos/xbox.py
Labels: enhancement

#5129 CFG: Add MemoryLoadResolver.
  angr/analyses/cfg/indirect_jump_resolvers/__init__.py
  angr/analyses/cfg/indirect_jump_resolvers/default_resolvers.py
  angr/analyses/cfg/indirect_jump_resolvers/memload_resolver.py
Labels: enhancement

#5130 ConstantResolver: Use FCP. Bail early when unresolvable.
  angr/analyses/cfg/indirect_jump_resolvers/const_resolver.py
Labels: enhancement

#5132 X86PeIatResolver: Support tail-call optimized functions.
  angr/analyses/cfg/indirect_jump_resolvers/x86_pe_iat.py
Labels: enhancement

#5131 IndirectJumpResolvers: Load valid addrs from writable regions.
  angr/analyses/cfg/indirect_jump_resolvers/propagator_utils.py
Labels: enhancement

#5133 CFGModel: Build node index on-demand; Use SortedList to reduce complexity.
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: enhancement

#5134 CFGBase: Force fastpath when calling model.get_any_node().
  angr/analyses/cfg/cfg_base.py
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: enhancement

#5135 Function._register_nodes: Only add node if it does not exist in the graph.
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#5136 CFGBase._make_functions: Reduce unnecessary function copying.
  angr/analyses/cfg/cfg_base.py
Labels: bug

#5138 Make SegmentList slightly faster
  angr/utils/segment_list.py
Labels: enhancement, refactor

#5140 Function: Remove block cache.
  angr/knowledge_plugins/functions/function.py
Labels: enhancement

#5141 CFG: Use weakrefs to reduce memory footprint.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/cfg/cfg_fast_soot.py
  angr/codenode.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
Labels: enhancement

#5139 Function: Avoid storing duplicate BlockNodes.
  angr/analyses/cfg/cfg_base.py
  angr/analyses/cfg/cfg_emulated.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/function_manager.py
  angr/knowledge_plugins/functions/function_parser.py
  angr/knowledge_plugins/functions/soot_function.py
Labels: bug

#5142 Decompiler: Support __rust_probestack.
  angr/analyses/cfg/cfg_fast.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/stack_pointer_tracker.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5143 Clinic._replace_single_target_indirect_transitions: Mute 'not hooked' warnings.
  angr/analyses/decompiler/clinic.py
Labels: enhancement

#5146 CFGFast: Ensure the existence of function address before calling get_by_addr()
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/functions/function_manager.py
Labels: refactor

#5152 EnumsConv: Support Ijk_Sys_int.
  angr/protos/__init__.py
  angr/protos/cfg.proto
  angr/protos/cfg_pb2.py
  angr/protos/function.proto
  angr/protos/function_pb2.py
  angr/protos/primitives.proto
  angr/protos/primitives_pb2.py
  angr/protos/variables_pb2.py
  angr/protos/xrefs.proto
  angr/protos/xrefs_pb2.py
  angr/utils/enums_conv.py
Labels: enhancement

#5153 SimStackVariable: Force offset to be within int32 range during serialization.
  angr/sim_variable.py
  tests/serialization/test_serialization.py
Labels: bug

#5154 CFGModel serialization: Resilience against new jumpkinds.
  angr/knowledge_plugins/cfg/cfg_model.py
Labels: enhancement

#5157 Decompiler: Correctly handle __chkstk.
  angr/analyses/decompiler/clinic.py
  angr/analyses/stack_pointer_tracker.py
Labels: enhancement

#5158 Decompiler: Fix -0x10000; fix incorrect masking in SSA.
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/structured_codegen/c.py
Labels: bug

#5163 CStructuredCodeGen: Support printing block addrs and vvar IDs.
  angr/analyses/decompiler/structured_codegen/c.py
Labels: enhancement

#5165 SequenceWalker: Update condition of ConditionNode.
  angr/analyses/decompiler/sequence_walker.py
Labels: bug

#5166 CCA: Turn off progress bar upon completion.
  angr/analyses/complete_calling_conventions.py
Labels: bug

#5164 Decompiler: Multiple fixes on TSSA variables, function args, and variable unification.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/dephication/dephication_base.py
  angr/analyses/decompiler/dephication/rewriting_engine.py
  angr/analyses/decompiler/dephication/seqnode_dephication.py
  angr/analyses/decompiler/ssailification/rewriting.py
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/decompiler/ssailification/ssailification.py
  angr/analyses/decompiler/ssailification/traversal.py
  angr/analyses/decompiler/ssailification/traversal_state.py
  angr/analyses/s_propagator.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
  angr/analyses/s_reaching_definitions/s_rda_view.py
  angr/analyses/s_reaching_definitions/s_reaching_definitions.py
  angr/analyses/variable_recovery/engine_ail.py
  angr/analyses/variable_recovery/engine_base.py
  angr/analyses/variable_recovery/engine_vex.py
  angr/analyses/variable_recovery/variable_recovery_fast.py
  angr/knowledge_plugins/variables/variable_manager.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5167 AILSimplifier: Do not replace phi vars when unifying local vars.
  angr/analyses/decompiler/ail_simplifier.py
Labels: bug

#5169 FactCollector: Properly handle tail-call optimizations.
  angr/analyses/calling_convention/fact_collector.py
Labels: bug

#5170 CFG: Add support to a new type of jumptable.
  angr/analyses/cfg/indirect_jump_resolvers/jumptable.py
  tests/analyses/cfg/test_jumptables.py
Labels: enhancement

#5171 SSA: Fix support for partial regs.
  angr/analyses/decompiler/ssailification/ssailification.py
Labels: enhancement

#5172 Decompiler: Support decompiling amd64-no-ob-check jumptables.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/utils.py
  angr/analyses/variable_recovery/engine_ail.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5173 CCA: Ensure the block is not empty before getting its last insn.
  angr/analyses/calling_convention/calling_convention.py
Labels: bug

#5174 CFG: Outsource is_noop_block check to native land.
  angr/analyses/cfg/cfg_base.py
  tests/analyses/cfg/test_noop_blocks.py
Labels: enhancement

#5175 Function: Drop unused prepared_registers and friends.
  angr/analyses/cfg/cfg_emulated.py
  angr/knowledge_plugins/functions/function.py
  angr/knowledge_plugins/functions/soot_function.py
Labels: refactor

#5176 Allow pcode syscalls
  angr/engines/pcode/emulate.py
  angr/engines/successors.py
  tests/engines/pcode/test_emulate.py
Labels: enhancement

#5180 CFG (and vex lifter): Use clemory readonly view when possible.
  angr/analyses/cfg/cfg_fast.py
  angr/block.py
  angr/engines/pcode/lifter.py
  angr/engines/vex/lifter.py
Labels: enhancement

#5181 RDA: Fix a crash caused by missing prototype libname in SIM_LIBRARIES.
  angr/analyses/reaching_definitions/function_handler.py
Labels: bug

#5182 Fix invalid init and fini labels at 0.
  angr/analyses/cfg/cfg_fast.py
  angr/procedures/glibc/__libc_start_main.py
Labels: bug

#5185 PeepholeOpt: Remove unnecessary negations around comparisons.
  angr/analyses/decompiler/peephole_optimizations/remove_redundant_nots.py
Labels: enhancement

#5187 SPropagator: Allow propagating Load exprs across blocks.
  angr/analyses/complete_calling_conventions.py
  angr/analyses/decompiler/optimization_passes/flip_boolean_cmp.py
  angr/analyses/s_propagator.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5190 ReturnDuplicatorHigh: Delay the generation of RI until necessary.
  angr/analyses/decompiler/optimization_passes/return_duplicator_high.py
Labels: refactor

#5193 Clinic: Fix missing edge data after ITE rewrite.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/decompiler.py
Labels: bug

#5194 APIObfuscationFinder: Deobfuscate globals initialized by GetProcAddress
  angr/analyses/deobfuscator/api_obf_finder.py
  angr/analyses/deobfuscator/api_obf_type2_finder.py
  angr/knowledge_plugins/obfuscations.py
  tests/analyses/test_api_obf_finder.py
Labels: enhancement

#5195 Labels: Fix and test get_unique_label
  angr/knowledge_plugins/labels.py
  tests/knowledge_plugins/test_labels.py
Labels: bug

#5197 CFGFast: support unmapped RO regions in register_readonly_regions.
  angr/analyses/cfg/cfg_fast.py
Labels: enhancement

#5196 CFGFast: Fix robustness issues in _process_irsb_data_ref_inlined_data.
  angr/analyses/cfg/cfg_fast.py
  angr/knowledge_plugins/cfg/cfg_model.py
  angr/knowledge_plugins/xrefs/xref_manager.py
  tests/analyses/test_xrefs.py
Labels: bug

#5200 FactCollector: Support aligning sp.
  angr/analyses/calling_convention/fact_collector.py
Labels: enhancement

#5199 StructuredCodeGen: Fix displaying of small integers as variable references.
  angr/analyses/decompiler/structured_codegen/c.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5201 FactCollector: Fix conflicts between callee-restored regs and return value regs.
  angr/analyses/calling_convention/fact_collector.py
  angr/calling_conventions.py
Labels: bug

#5204 ConditionConstantPropagation and a fix.
  angr/analyses/decompiler/clinic.py
  angr/analyses/decompiler/condition_processor.py
  angr/analyses/decompiler/optimization_passes/__init__.py
  angr/analyses/decompiler/optimization_passes/condition_constprop.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/presets/fast.py
  angr/analyses/decompiler/presets/full.py
  angr/analyses/decompiler/structuring/phoenix.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug, enhancement

#5205 Duplicate returns early to enable more propagation.
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
  angr/analyses/decompiler/optimization_passes/return_duplicator_high.py
  angr/analyses/decompiler/peephole_optimizations/eager_eval.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5207 CallSiteMaker: Fix incorrect stack args recognized when sizes do not match.
  angr/analyses/decompiler/callsite_maker.py
  angr/analyses/s_reaching_definitions/s_rda_view.py
  tests/analyses/decompiler/test_decompiler.py
Labels: bug

#5210 ReturnDuplicator: Dup return statements without retexprs.
  angr/analyses/decompiler/optimization_passes/return_duplicator_base.py
Labels: enhancement

#5212 AILSimplifier: Remove vvar cycles involving both phi and reg vars.
  angr/analyses/decompiler/ail_simplifier.py
Labels: enhancement

#5211 Structurer: Prioritize addrs within the region as switch_end_addr.
  angr/analyses/decompiler/structuring/dream.py
  angr/analyses/decompiler/structuring/phoenix.py
  angr/analyses/decompiler/structuring/structurer_base.py
  angr/analyses/decompiler/structuring/structurer_nodes.py
Labels: bug

#5213 Decompiler: Propagate stack-based switch exprs.
  angr/analyses/decompiler/ssailification/rewriting_engine.py
  angr/analyses/s_propagator.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5209 Allow removing dead stack vars discovered by SPropagator.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/block_simplifier.py
  angr/analyses/decompiler/clinic.py
  angr/analyses/s_propagator.py
  tests/analyses/decompiler/test_decompiler.py
Labels: enhancement

#5222 ExprFolding: Ensure non-interference when folding expressions.
  angr/analyses/decompiler/ail_simplifier.py
  angr/analyses/decompiler/decompiler.py
  angr/analyses/decompiler/expression_narrower.py
  angr/analyses/decompiler/optimization_passes/ite_region_converter.py
  angr/analyses/decompiler/optimization_passes/optimization_pass.py
  angr/analyses/decompiler/region_simplifiers/expr_folding.py
  angr/analyses/decompiler/region_simplifiers/region_simplifier.py
  angr/analyses/s_propagator.py
  angr/analyses/s_reaching_definitions/s_rda_model.py
  angr/knowledge_plugins/key_definitions/atoms.py
  angr/utils/ssa/__init__.py
  tests/analyses/decompiler/test_decompiler.py
  tests/analyses/test_api_obf_finder.py
Labels: bug
